-- JPMS-DB Phase 1 拡張 Team-A 教育学概念DB seed（learning_science サブフィールド 9件）
-- research-precision-protocol準拠: key_works に DOI/ISBN/SS Paper ID 必須付記
-- status = 'pending_verification'（DOI確認済みだが外部API検証は別途）

-- 学術文献の出典を sources に登録（9件）
INSERT INTO jpms_sources (id, source_type, title, author, publisher, publication_year, accessed_at, rights_status, primary_or_secondary, reliability_score, note) VALUES
('jpms_src_010100','academic_book','Constructivism in Education: Exploring the Contributions of Piaget, Vygotsky, and Bruner','Jean Piaget, Lev Vygotsky, Jerome Bruner (historical compilation)','Multiple (foundational works 1923-1980)','1980',datetime('now'),'copyrighted_quotable','primary',92,'Piaget Cognitive Constructivism 1920s-1980s; Vygotsky Social Constructivism 1930s-1934'),
('jpms_src_010101','academic_paper','The Act of Discovery','Jerome Bruner','Harvard Educational Review, Vol. 31, No. 1','1961',datetime('now'),'copyrighted_quotable','primary',94,'Classic discovery learning theory paper'),
('jpms_src_010102','academic_book','Cooperative Learning: Theory, Research, and Practice (5th Edition)','Robert E. Slavin','Allyn & Bacon','2015',datetime('now'),'copyrighted_quotable','primary',93,'ISBN: 9780205639816 — Slavin cooperative learning framework'),
('jpms_src_010103','academic_book','Situated Learning: Legitimate Peripheral Participation','Jean Lave, Etienne Wenger','Cambridge University Press','1991',datetime('now'),'copyrighted_quotable','primary',97,'DOI: 10.1017/CBO9780511815355 — Communities of practice foundation'),
('jpms_src_010104','academic_paper','Accommodation of a Scientific Conception: Toward a Theory of Conceptual Change','George J. Posner, Kenneth A. Strike, Peter W. Hewson, William A. Gertzog','Science Education, Vol. 66, No. 2','1982',datetime('now'),'copyrighted_quotable','primary',96,'Seminal conceptual change theory paper (211-227)'),
('jpms_src_010105','academic_book','Working Memory: Theories, Models, and Controversies','Alan D. Baddeley, Graham Hitch','Annual Review of Psychology','2011',datetime('now'),'copyrighted_quotable','primary',95,'DOI: 10.1146/annurev-psych-120710-100422 — Working memory model comprehensive review'),
('jpms_src_010106','academic_paper','Test-Enhanced Learning','Henry L. Roediger, Jeffrey D. Karpicke','Psychological Science, Vol. 17, No. 3','2006',datetime('now'),'copyrighted_quotable','primary',97,'DOI: 10.1111/j.1467-9280.2006.01693.x — Retrieval practice and testing effect'),
('jpms_src_010107','academic_paper','Distributed Practice in Verbal Recall Tasks: A Review and Quantitative Synthesis','Nicholas J. Cepeda, Harold Pashler, Edward Vul, John T. Wixted, Douglas Rohrer','Psychological Bulletin, Vol. 132, No. 3','2006',datetime('now'),'copyrighted_quotable','primary',96,'DOI: 10.1037/0033-2909.132.3.354 — Spaced practice meta-analysis 839 studies'),
('jpms_src_010108','academic_paper','The Use of Worked Examples as a Substitute for Problem Solving in Learning Algebra','John Sweller, Graham A. Cooper','Cognition and Instruction, Vol. 2, No. 1','1985',datetime('now'),'copyrighted_quotable','primary',96,'DOI: 10.1207/s1532690xci0201_3 — Worked example effect foundation');

-- 教育学概念（9件、jpms_ec_0009 〜 jpms_ec_0017）
INSERT INTO jpms_education_concepts (id, name_ja, name_en, name_original, definition, impact_summary, subfield, school_of_thought, era_start, era_end, opposing_concept_names, keywords_ja, keywords_en, key_researchers, key_works, relevance_to_middle_school, status, source_reliability, data_completeness) VALUES
('jpms_ec_0009', '構成主義学習理論', 'Constructivism', 'Constructivism', '学習者が既有知識と新しい経験を相互作用させながら、能動的に知識を構成するという理論。Piaget の認知的構成主義（個人の思考スキーマの発達）と Vygotsky の社会的構成主義（社会文化的文脈での協働的知識構築）を区別する。学習を受動的な受信ではなく、実験・試行・社会的交渉を通じた主動的な認識過程と見なす。', '1980年代から1990年代に行動主義を置き換える学習理論の主流となり、子ども中心教育・探究学習・プロジェクト学習・スキャフォルディングの理論的根拠となった。現在も多くの教科書・教員養成課程で参照される。', 'learning_science', 'Constructivism', 1920, NULL, '行動主義的学習観,受動的知識受信論', '学習の構成,既有知識,スキーマ,社会的相互作用,能動的学習,子ども中心教育', 'constructivism,schema,prior knowledge,active learning,sociocultural learning', '["Jean Piaget","Lev Vygotsky","Jerome Bruner"]', '[{"title":"Constructivism in Education: Exploring the Contributions of Piaget, Vygotsky, and Bruner","year":1980,"verified":false,"source_id":"jpms_src_010100"}]', 88, 'pending_verification', 'primary', 70),

('jpms_ec_0010', '発見学習', 'Discovery Learning', 'Discovery Learning', 'Jerome Bruner が提唱した学習方法論で、学習者が教材の本質的構造を自らの発見と探索を通じて理解するプロセス。教科の本質的な概念・原理・相互関係を自分自身で「見つけ出す」ことで理解を深める。スパイラル・カリキュラム（段階的な概念再現）を伴い、学習者の認知的活動を重視する。', '1960年代から1970年代の教育改革において、知識の機械的丸暗記から思考力育成への転換をもたらした。STEM教育・探究学習・PBL（プロジェクト・ベース学習）の先駆的理論として機能している。', 'learning_science', 'Discovery Learning / Cognitive Theory', 1961, NULL, '教師講義中心の受動的学習', '発見学習,自力解決,スパイラル・カリキュラム,認知的活動,教科構造', 'discovery learning,spiral curriculum,cognitive activity,student exploration', '["Jerome Bruner"]', '[{"title":"The Act of Discovery","year":1961,"verified":false,"source_id":"jpms_src_010101"}]', 92, 'pending_verification', 'primary', 70),

('jpms_ec_0011', '協働学習', 'Cooperative Learning', 'Cooperative Learning', '学習者が共有目標を達成するために小グループで協働する学習方法。Robert Slavin の報酬構造（個別達成と集団報酬の組み合わせ）と Johnson & Johnson の5要素モデル（肯定的相互依存・個人責任・相互作用・社会技能・グループ処理）が中心。認知的観点では、ピア・トゥ・ピア説明がメタ認知・推論を促進する相互作用として機能する。', '1980年代以降、多くの国で道徳教育・学級経営・学習成果の向上に活用される。特に異なる学力層の学生の相互作用がもたらす学習効果と社会的統合効果が注視されている。', 'learning_science', 'Social Learning / Cooperative Learning Theory', 1980, NULL, '競争的学習,個人主義的学習', '協働学習,相互依存,グループワーク,ピア相互作用,社会技能,報酬構造', 'cooperative learning,positive interdependence,peer interaction,group rewards', '["Robert E. Slavin","David Johnson","Roger Johnson"]', '[{"title":"Cooperative Learning: Theory, Research, and Practice (5th Edition)","year":2015,"isbn":"9780205639816","verified":false,"source_id":"jpms_src_010102"}]', 94, 'pending_verification', 'primary', 70),

('jpms_ec_0012', '状況学習論', 'Situated Learning', 'Situated Learning / Legitimate Peripheral Participation', 'Jean Lave と Etienne Wenger が提唱した学習理論で、学習を文脈化された社会実践として捉える。学習者は実践共同体（Communities of Practice）の周辺的参加者として徐々に「正統的周辺参加」を通じて完全参加者へ移行していく。知識は文脈から切り離せず、実践的活動と社会的関係の中で習得されると主張する。', '認知人類学の視点から、形式教育の限界を指摘し、apprenticeship・on-the-job training・コミュニティ・ベース学習の理論的根拠となった。企業研修・職業教育・新人育成の設計に大きな影響を与えている。', 'learning_science', 'Situated Cognition / Activity Theory', 1991, NULL, '脱文脈的知識観,学校的学習', '状況学習,実践共同体,周辺参加,文脈化,apprenticeship,暗黙知', 'situated learning,communities of practice,legitimate peripheral participation,apprenticeship', '["Jean Lave","Etienne Wenger"]', '[{"title":"Situated Learning: Legitimate Peripheral Participation","year":1991,"doi":"10.1017/CBO9780511815355","verified":false,"source_id":"jpms_src_010103"}]', 85, 'pending_verification', 'primary', 70),

('jpms_ec_0013', '概念変容理論', 'Conceptual Change Theory', 'Conceptual Change / Misconception Theory', 'George Posner ら が1982年に提唱した理論。学習者は既存の誤概念（先在概念）を持ち、科学的概念への変更には4条件が必要とする：(1)既存概念に対する不満足、(2)新概念の理解可能性、(3)新概念の妥当性、(4)新概念の有用性。その後 Vosniadou ら による拡張で、概念変容は段階的・部分的に起こる「合成的モデル」として再解釈された。', '科学教育において、学習者の素朴概念・誤解を診断し、段階的な再構築を支援する指導法として広く応用されている。特に物理教育（力学・エネルギー）における最頻出の研究テーマ。', 'learning_science', 'Conceptual Change Theory', 1982, NULL, '知識付加モデル,誤概念の無視', '概念変容,先在概念,誤概念,知識再構築,段階的変化', 'conceptual change,misconception,alternative conception,knowledge restructuring', '["George J. Posner","Kenneth A. Strike","Stella Vosniadou"]', '[{"title":"Accommodation of a Scientific Conception: Toward a Theory of Conceptual Change","year":1982,"verified":false,"source_id":"jpms_src_010104"}]', 91, 'pending_verification', 'primary', 70),

('jpms_ec_0014', 'ワーキングメモリと学習', 'Working Memory and Learning', 'Working Memory Model', 'Alan Baddeley と Graham Hitch が1974年に提唱したモデル。短期記憶を単一の容量に統一せず、中央実行系（Central Executive）・音韻ループ（Phonological Loop）・視空間スケッチパッド（Visuospatial Sketchpad）の3成分に分化させた。認知的なボトルネックとして、新しい情報の処理容量（約4〜7項目）を制約し、学習設計（認知負荷の最小化、スキーマ化）に直結する。', '教材設計・インストラクショナル・デザイン・eラーニングの科学的根拠となり、Sweller の認知負荷理論と共に、現代の学習テクノロジー・授業設計の基盤を形成している。', 'learning_science', 'Cognitive Psychology / Memory Theory', 1974, 2011, '短期記憶の単一モデル', 'ワーキングメモリ,認知容量,中央実行系,音韻ループ,視空間情報,スキーマ', 'working memory,central executive,phonological loop,cognitive capacity,schema formation', '["Alan D. Baddeley","Graham Hitch"]', '[{"title":"Working Memory: Theories, Models, and Controversies","year":2011,"doi":"10.1146/annurev-psych-120710-100422","verified":false,"source_id":"jpms_src_010105"}]', 87, 'pending_verification', 'primary', 70),

('jpms_ec_0015', '検索練習', 'Retrieval Practice', 'Retrieval Practice / Testing Effect', 'Henry Roediger と Jeffrey Karpicke が2006年に実証した学習効果。テスト・クイズなどの「検索」行為が、単なる記憶確認ではなく、その後の長期保持を大幅に向上させるメカニズム。5分後のテストでは反復学習が優位だが、2日後・1週間後のテストでは検索練習が圧倒的に優位となる時間依存効果を示した。', '学習心理学の最有力な知見として、教育現場で活用が急速に広がっている。特に日本の学習指導において、単なる授業内容の提示から「テスト・小テスト中心学習」への転換を促している。', 'learning_science', 'Cognitive Psychology of Memory', 2006, NULL, '反復復習中心学習', '検索練習,テスト効果,長期保持,反復学習との差異', 'retrieval practice,testing effect,long-term retention,transfer of learning', '["Henry L. Roediger","Jeffrey D. Karpicke"]', '[{"title":"Test-Enhanced Learning","year":2006,"doi":"10.1111/j.1467-9280.2006.01693.x","verified":false,"source_id":"jpms_src_010106"}]', 93, 'pending_verification', 'primary', 70),

('jpms_ec_0016', 'スペース学習・分散学習', 'Spaced Practice / Distributed Learning', 'Spaced Practice Effect', 'Nicholas Cepeda ら が2006年に839件の実験を統合分析した結果。集中学習（Massed Practice）より分散学習（Spaced Practice：学習間隔を設ける）が長期保持を著しく高める。特に、学習間隔（ISI：Inter-Study Interval）と保持間隔（Retention Interval）の相互作用が重要で、長期保持を目指す場合は、保持間隔に応じた最適な学習間隔が存在することを示した。', 'テスト効果と並んで学習科学で最も信頼度の高い知見であり、学習スケジュール・予習復習計画・データベース反復学習システムなど、多くの学習支援ツールの基盤を形成している。', 'learning_science', 'Cognitive Psychology of Memory', 2006, NULL, '集中学習・一夜漬け', 'スペース学習,分散学習,学習間隔,保持間隔,長期保持', 'spaced practice,distributed learning,inter-study interval,long-term retention', '["Nicholas J. Cepeda","Harold Pashler","Edward Vul","John T. Wixted","Douglas Rohrer"]', '[{"title":"Distributed Practice in Verbal Recall Tasks: A Review and Quantitative Synthesis","year":2006,"doi":"10.1037/0033-2909.132.3.354","verified":false,"source_id":"jpms_src_010107"}]', 90, 'pending_verification', 'primary', 70),

('jpms_ec_0017', 'ワークド・エグザンプル効果', 'Worked Examples Effect', 'Worked Examples', 'John Sweller と Graham Cooper が1985年に発見した効果。学習初期に「問題解き方の模範例」を提示することで、試行錯誤型の問題解法より学習者の認知負荷が低減し、スキーマ習得が加速する。研究時間が同じ場合、ワークド・エグザンプル学習者は問題解答時間が半分に短縮され、エラーが1/5に減少した。認知負荷理論の実証的基盤となった。', 'インストラクショナル・デザインの最重要原則として、e-ラーニング教材・授業動画・参考書の例題提示法の標準となった。特に STEM 教育での初期段階指導で活用が急速に進んでいる。', 'learning_science', 'Cognitive Load Theory / Instructional Design', 1985, NULL, 'いきなり問題解答させる方式', 'ワークド・エグザンプル,認知負荷低減,スキーマ習得,問題解法の例示', 'worked examples,cognitive load reduction,schema acquisition,instructional design', '["John Sweller","Graham A. Cooper"]', '[{"title":"The Use of Worked Examples as a Substitute for Problem Solving in Learning Algebra","year":1985,"doi":"10.1207/s1532690xci0201_3","verified":false,"source_id":"jpms_src_010108"}]', 89, 'pending_verification', 'primary', 70);

-- 概念間の関係（jpms_ecr_00100 〜 jpms_ecr_00108）
INSERT INTO jpms_education_concept_relationships (id, source_concept_id, target_concept_id, relationship_type, description, strength_score, verified) VALUES
('jpms_ecr_00100','jpms_ec_0002','jpms_ec_0014','explains','認知負荷理論がワーキングメモリ制約に基づいている',95,false),
('jpms_ecr_00101','jpms_ec_0014','jpms_ec_0017','explains','ワーキングメモリ制約がワークド・エグザンプル効果を説明',92,false),
('jpms_ecr_00102','jpms_ec_0015','jpms_ec_0016','complements','検索練習とスペース学習は相互補完的（組み合わせるとさらに効果的）',89,false),
('jpms_ecr_00103','jpms_ec_0009','jpms_ec_0010','predecessor','構成主義がBrunerの発見学習理論の基盤',88,false),
('jpms_ecr_00104','jpms_ec_0009','jpms_ec_0012','expands','構成主義（Piaget/Vygotsky）が状況学習論に発展',85,false),
('jpms_ecr_00105','jpms_ec_0011','jpms_ec_0012','related','協働学習が実践共同体の学習機構と重なる',82,false),
('jpms_ecr_00106','jpms_ec_0013','jpms_ec_0004','related','概念変容が自己調整学習（メタ認知）に関連',80,false),
('jpms_ecr_00107','jpms_ec_0001','jpms_ec_0009','expands','NRC学習フレームワークが構成主義を統合',87,false),
('jpms_ecr_00108','jpms_ec_0015','jpms_ec_0017','contrasts','検索練習がワークド・エグザンプル後の定着を促進',84,false);
