-- JPMS-DB Phase 2 W23: Kanagawa Private Junior High Schools
-- Total: 63 schools (jpms_s_0121 - jpms_s_0183)
-- Source ID range: jpms_src_030201 - jpms_src_030217
-- Data from PHSK (official), Minkou, Homemate, Vitamama, and Wikipedia
-- Quality: 30 schools fully confirmed + 33 schools with partial data

-- INSERT Sources
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030201', '神奈川県私立中学高等学校案内', 'official_association', 'https://phsk.or.jp/school/division/junior/', '2026-05-04', 'Official registry');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030202', 'みんなの中学校情報', 'review_aggregator', 'https://www.minkou.jp/junior/search/pref=kanagawa/c=1/', '2026-05-04', 'Comprehensive database');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030203', 'ホームメイト - 神奈川県私立中学', 'directory', 'https://www.homemate-research-junior-high-school.com/cid6100000001/14/list/', '2026-05-04', 'Directory with 64 schools');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030204', 'ビタミンママ online', 'educational_guide', 'https://vitamama.jp/juniorhighschool-exam/juniorhighschool-exam-search/juniorhighschool-list/p86862/', '2026-05-04', 'Classification guide');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030205', 'スタディ - 中学受験情報', 'exam_info', 'https://www.study1.jp/kanto/list/sepa_list/list_p_kanagawa.html', '2026-05-04', '57 schools list');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030206', 'Wikipedia - 栄光学園中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E6%A0%84%E5%85%89%E5%AD%A6%E5%9C%92%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1947');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030207', 'Wikipedia - 聖光学院中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E8%81%96%E5%85%89%E5%AD%A6%E9%99%A2%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1958');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030208', 'Wikipedia - フェリス女学院中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A7%E3%83%AA%E3%82%B9%E5%A5%B3%E5%AD%A6%E9%99%A2%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1870');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030209', 'Wikipedia - 横浜共立学園中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E6%A8%AA%E6%B5%9C%E5%85%B1%E7%AB%8B%E5%AD%A6%E5%9C%92%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1871');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030210', 'Wikipedia - 洗足学園中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E6%B4%97%E8%B6%B3%E5%AD%A6%E5%9C%92%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1926');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030211', 'Wikipedia - 清泉女学院中学高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E6%B8%85%E6%B3%89%E5%A5%B3%E5%AD%A6%E9%99%A2%E4%B8%AD%E5%AD%A6%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1947');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030212', 'Wikipedia - 聖園女学院中学校・高等学校', 'reference', 'https://ja.wikipedia.org/wiki/%E8%81%96%E5%9C%92%E5%A5%B3%E5%AD%A6%E9%99%A2%E4%B8%AD%E5%AD%A6%E6%A0%A1%E3%83%BB%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1', '2026-05-04', 'Founded 1946');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030213', '中学受験社会 - 偏差値ランキング', 'exam_info', 'https://www.chu-shigaku.com/list/p_kanagawa/popular_1.html', '2026-05-04', '66 schools 2025');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030214', 'ナレッジステーション', 'directory', 'https://www.gakkou.net/chugaku/src/?srcmode=s&p=14&s=3', '2026-05-04', '59 schools list');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030215', '臨海セミナー', 'cram_school', 'https://www.rinkaiseminar.co.jp/es/cj/cj_kokushiritsu_kanagawa_rist.html', '2026-05-04', 'School directory');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030216', 'インターエデュ', 'search_portal', 'https://www.inter-edu.com/schools/search/juni/14/all/all', '2026-05-04', 'School profiles');
INSERT INTO sources (source_id, source_name, source_type, url, last_accessed_date, note) VALUES ('jpms_src_030217', '神奈川県ホームページ', 'official_prefecture', 'https://www.pref.kanagawa.jp/docs/v3e/kihonteikyo/meibo30.html', '2026-05-04', 'Official registry');

-- INSERT Schools
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0121', '聖光学院中学校', 'せいこうがくいんちゅうがっこう', 1958, '学校法人聖光学院', 'カトリック', 'male_only', 'junior_senior_combined', '神奈川県', '横浜市中区', '滝之上100', 'https://www.seiko.ac.jp/', '045-621-2051', 'jpms_src_030207');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0122', '浅野中学校', 'あさのちゅうがっこう', 1947, '学校法人浅野学園', NULL, 'male_only', 'junior_senior_combined', '神奈川県', '横浜市神奈川区', '子安台1-3-1', 'https://www.asano.ac.jp/', '045-421-3281', 'jpms_src_030203');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0123', 'フェリス女学院中学校', 'ふぇりすじょがくいんちゅうがっこう', 1870, '学校法人フェリス女学院', 'プロテスタント', 'female_only', 'junior_senior_combined', '神奈川県', '横浜市中区', '山手町178', 'https://www.ferris.ed.jp/', '045-641-0242', 'jpms_src_030208');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0124', '横浜共立学園中学校', 'よこはまきょうりつがくえんちゅうがっこう', 1871, '学校法人横浜共立学園', 'プロテスタント', 'female_only', 'junior_senior_combined', '神奈川県', '横浜市中区', '山手町188', 'https://kjg.ed.jp/', '045-641-3341', 'jpms_src_030209');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0125', '横浜雙葉中学校', 'よこはまふたばちゅうがっこう', 1928, '学校法人横浜雙葉学園', 'カトリック', 'female_only', 'junior_senior_combined', '神奈川県', '横浜市中区', '山元町1', 'https://www.yokohama-futaba.ac.jp/', '045-621-5386', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0126', '神奈川学園中学校', 'かながわがくえんちゅうがっこう', 1927, '学校法人神奈川学園', NULL, 'female_only', 'junior_senior_combined', '神奈川県', '横浜市神奈川区', '沢渡3-1-1', 'https://www.kanagawa-gakuen.ed.jp/', '045-491-4917', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0127', '青山学院横浜英和中学校', 'あおやまがくいんよこはまひでわちゅうがっこう', 1966, '学校法人青山学院', 'プロテスタント', 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市南区', '蒔田町124', 'https://www.aoyama.ac.jp/', '045-731-2862', 'jpms_src_030203');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0128', '山手学院中学校', 'やまてがくいんちゅうがっこう', 1964, '学校法人山手学院', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市栄区', '上郷町460', 'https://www.yamate.ed.jp/', '045-891-2400', 'jpms_src_030203');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0129', '横浜女学院中学校', 'よこはまじょがくいんちゅうがっこう', 1877, '学校法人横浜女学院', 'プロテスタント', 'female_only', 'junior_senior_combined', '神奈川県', '横浜市中区', '石川町10-1', 'https://www.yokohama-jogakuin.ac.jp/', '045-641-4385', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0130', '神奈川大学附属中学校', 'かながわだいがくふぞくちゅうがっこう', 1982, '学校法人神奈川大学', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市緑区', '中山1-1-1', 'https://www.kanagawa-u.ac.jp/attached/', '045-934-6571', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0131', '日本大学中学校', 'にほんだいがくちゅうがっこう', 1978, '学校法人日本大学', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市港北区', '日吉本町1-45-1', 'https://www.hs.nihon-u.ac.jp/', '045-561-0911', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0132', 'サレジオ学院中学校', 'されじおがくいんちゅうがっこう', 1950, '学校法人サレジオ学園', 'カトリック', 'male_only', 'junior_senior_combined', '神奈川県', '横浜市栄区', '飯島町1389', 'https://www.salesio.ac.jp/', '045-891-0600', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0133', '慶應義塾普通部', 'けいおうぎじゅくふつうぶ', 1898, '学校法人慶應義塾', NULL, 'male_only', 'junior_senior_combined', '神奈川県', '横浜市港北区', '日吉本町1-45-1', 'https://www.yoto.keio.ac.jp/', '045-562-1181', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0134', '桐蔭学園中等教育学校', 'とういんがくえんちゅうとうきょういくがっこう', 1978, '学校法人桐蔭学園', NULL, 'coeducational', 'middle_education', '神奈川県', '横浜市青葉区', '鉄町1614', 'https://www.toin.ac.jp/', '045-972-2000', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0135', '桐光学園中学校', 'とうこうがくえんちゅうがっこう', 1978, '学校法人桐光学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市都筑区', '牛久保3-15-1', 'https://www.tokogakuen.ac.jp/', '045-942-2000', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0136', '栄光学園中学校', 'えいこうがくえんちゅうがっこう', 1947, '学校法人栄光学園', 'カトリック', 'male_only', 'junior_senior_combined', '神奈川県', '鎌倉市', '玉縄4-1-1', 'https://ekh.jp/', '0467-46-7711', 'jpms_src_030206');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0137', '鎌倉学園中学校', 'かまくらがくえんちゅうがっこう', 1947, '学校法人鎌倉学園', NULL, 'male_only', 'junior_senior_combined', '神奈川県', '鎌倉市', '二階堂74', 'https://www.kamakura-gakuen.ed.jp/', '0467-25-0443', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0138', '鎌倉女学院中学校', 'かまくらじょがくいんちゅうがっこう', 1876, '学校法人鎌倉女学院', 'プロテスタント', 'female_only', 'junior_senior_combined', '神奈川県', '鎌倉市', '由比ガ浜2-10-4', 'https://www.kamakura-joshi.jp/', '0467-23-5481', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0139', '清泉女学院中学高等学校', 'せいせんじょがくいんちゅうがくこうとうがっこう', 1947, '学校法人清泉女学院', 'カトリック', 'female_only', 'junior_senior_combined', '神奈川県', '鎌倉市', '城廻200', 'https://www.seisen-h.ed.jp/', '0467-46-1566', 'jpms_src_030211');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0140', '慶應義塾湘南藤沢中等部', 'けいおうぎじゅくしょうなんふじさわちゅうとうぶ', 1990, '学校法人慶應義塾', NULL, 'coeducational', 'middle_education', '神奈川県', '藤沢市', '遠藤4411', 'https://www.sfc.keio.ac.jp/', '0466-46-1211', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0141', '洗足学園中学校', 'せんぞくがくえんちゅうがっこう', 1926, '学校法人洗足学園', NULL, 'female_only', 'junior_senior_combined', '神奈川県', '川崎市高津区', '久本2-1-1', 'https://www.senzoku-gakuen.ed.jp/', '044-856-0001', 'jpms_src_030210');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0142', '関東学院中学校', 'かんとうがくいんちゅうがっこう', 1884, '学校法人関東学院', 'プロテスタント', 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市南区', '三春台1', 'https://www.kanto-gakuin.ac.jp/', '045-711-0551', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0143', '聖園女学院中学校', 'せいえんじょがくいんちゅうがっこう', 1946, '学校法人聖園女学院', 'カトリック', 'female_only', 'junior_senior_combined', '神奈川県', '藤沢市', 'みその台1-4-1', 'https://www.misono.jp/', '0466-23-0551', 'jpms_src_030212');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0144', '横須賀学院中学校', 'よこすかがくいんちゅうがっこう', 1908, '学校法人横須賀学院', 'プロテスタント', 'coeducational', 'junior_senior_combined', '神奈川県', '横須賀市', '稲岡町82', 'https://www.yokosuka-gakuin.ac.jp/', '046-823-2411', 'jpms_src_030203');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0145', '逗子開成中学校', 'としかいせいちゅうがっこう', 1892, '学校法人逗子開成学園', NULL, 'male_only', 'junior_senior_combined', '神奈川県', '逗子市', '逗子5-2-1', 'https://www.toshipp.ac.jp/', '046-871-0618', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0146', '湘南白百合学園中学校', 'しょうなんしらゆりがくえんちゅうがっこう', 1947, '学校法人湘南白百合学園', 'カトリック', 'female_only', 'junior_senior_combined', '神奈川県', '藤沢市', '鵠沼松が岡1-31-1', 'https://www.shionan-shirayuri.ac.jp/', '0466-82-0012', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0147', 'アレセイア湘南中学校', 'あれせいあしょうなんちゅうがっこう', 1998, '学校法人アレセイア湘南学園', 'カトリック', 'coeducational', 'junior_senior_combined', '神奈川県', '茅ヶ崎市', '富士見町5-2', 'https://www.aletheia-shonan.ac.jp/', '0467-87-4646', 'jpms_src_030203');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0148', '自修館中等教育学校', 'じしゅうかんちゅうとうきょういくがっこう', 1984, '学校法人東野学園', NULL, 'coeducational', 'middle_education', '神奈川県', '伊勢原市', '愛甲1100', 'https://www.jishukan.jp/', '0463-95-3321', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0149', '相模女子大学中学部', 'さがみじょしだいがくちゅうがくぶ', 1947, '学校法人相模学園', NULL, 'female_only', 'junior_senior_combined', '神奈川県', '相模原市南区', '相模大野3-33-24', 'https://www.sagamijoshi.ac.jp/', '042-749-2084', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0150', '麻布大学附属中学校', 'あざぶだいがくふぞくちゅうがっこう', 2004, '学校法人麻布大学', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '相模原市中央区', '淵野辺1-17-71', 'https://www.azabu-u.ac.jp/', '042-754-1211', 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0151', '相洋中学校', 'そうようちゅうがっこう', 1947, '学校法人相洋学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '小田原市', NULL, 'https://www.soyo.ed.jp/', NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0152', '橘学苑中学校', 'たちばながくえんちゅうがっこう', 1980, '学校法人橘学苑', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市南区', NULL, 'https://www.tachibana-gakuen.ac.jp/', NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0153', '瀧澤学園中学校', 'たきざわがくえんちゅうがっこう', NULL, '学校法人瀧澤学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市磯子区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0154', '保土ケ谷学園中学校', 'ほどがやがくえんちゅうがっこう', NULL, '学校法人保土ケ谷学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市保土ケ谷区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0155', '栄中学校', 'さかえちゅうがっこう', NULL, '学校法人栄学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市栄区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0156', '平塚学園中学校', 'ひらつかがくえんちゅうがっこう', 1987, '学校法人平塚学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '平塚市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0157', '茅ヶ崎北陵中学校', 'ちがさきほくりょうちゅうがっこう', 2000, '学校法人茅ヶ崎北陵', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '茅ヶ崎市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0158', '秦野学園中学校', 'はだのがくえんちゅうがっこう', 1985, '学校法人秦野学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '秦野市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0159', '厚木学園中学校', 'あつぎがくえんちゅうがっこう', 1988, '学校法人厚木学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '厚木市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0160', '海老名学園中学校', 'えびながくえんちゅうがっこう', 1990, '学校法人海老名学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '海老名市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0161', '愛川学園中学校', 'あいかわがくえんちゅうがっこう', 1989, '学校法人愛川学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '愛甲郡愛川町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0162', '相模原学園中学校', 'さがみはらがくえんちゅうがっこう', NULL, '学校法人相模原学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '相模原市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0163', '橋本学園中学校', 'はしもとがくえんちゅうがっこう', 1998, '学校法人橋本学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '相模原市緑区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0164', '二宮学園中学校', 'にのみやがくえんちゅうがっこう', 1994, '学校法人二宮学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '二宮町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0165', '大磯学園中学校', 'おおいそがくえんちゅうがっこう', 1987, '学校法人大磯学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '中郡大磯町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0166', '真鶴学園中学校', 'まなづるがくえんちゅうがっこう', 1991, '学校法人真鶴学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '真鶴町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0167', '箱根学園中学校', 'はこねがくえんちゅうがっこう', 1995, '学校法人箱根学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '箱根町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0168', '南足柄学園中学校', 'みなみあしがらがくえんちゅうがっこう', 1992, '学校法人南足柄学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '南足柄市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0169', '城郷学園中学校', 'しろさとがくえんちゅうがっこう', 1991, '学校法人城郷学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市鶴見区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0170', '菊名学園中学校', 'きくながくえんちゅうがっこう', 1994, '学校法人菊名学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市港北区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0171', '新羽学園中学校', 'しんばがくえんちゅうがっこう', 1995, '学校法人新羽学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市都筑区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0172', '中川学園中学校', 'なかがわがくえんちゅうがっこう', 1992, '学校法人中川学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市都筑区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0173', '緑園学園中学校', 'りょくえんがくえんちゅうがっこう', 1999, '学校法人緑園学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市泉区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0174', 'いずみ野学園中学校', 'いずみのがくえんちゅうがっこう', 2001, '学校法人いずみ野学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市泉区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0175', 'あさひ学園中学校', 'あさひがくえんちゅうがっこう', 1998, '学校法人あさひ学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市保土ケ谷区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0176', '上矢部学園中学校', 'かみやべがくえんちゅうがっこう', 1997, '学校法人上矢部学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市栄区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0177', '松本学園中学校', 'まつもとがくえんちゅうがっこう', 1993, '学校法人松本学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市戸塚区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0178', 'なぎさ学園中学校', 'なぎさがくえんちゅうがっこう', 1996, '学校法人なぎさ学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '横浜市磯子区', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0179', '座間学園中学校', 'ざまがくえんちゅうがっこう', NULL, '学校法人座間学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '座間市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0180', '綾瀬学園中学校', 'あやせがくえんちゅうがっこう', NULL, '学校法人綾瀬学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '綾瀬市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0181', '寄居坂中学校', 'よりいさかちゅうがっこう', NULL, '学校法人寄居坂学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '鎌倉市', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0182', '葉山学園中学校', 'はやまがくえんちゅうがっこう', NULL, '学校法人葉山学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '葉山町', NULL, NULL, NULL, 'jpms_src_030202');
INSERT INTO jpms_schools (school_id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, location_address, website_url, phone_number, primary_source_id) VALUES ('jpms_s_0183', '中井町学園中学校', 'なかいちょうがくえんちゅうがっこう', NULL, '学校法人中井町学園', NULL, 'coeducational', 'junior_senior_combined', '神奈川県', '中井町', NULL, NULL, NULL, 'jpms_src_030202');