-- W34 Testimonials Collection: Top 10 Kanagawa Private Junior High Schools
-- Collected: May 2026
-- Coverage: Principal messages, graduate interviews, current student/parent voices
-- Total: 30 testimonials (3 per school x 10 schools)
-- Quality: quoted_with_attribution or anonymized_only, sourced from school websites/official publications

-- Source records for school websites and official publications
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040401', 'school_website', '浅野中学校・高等学校 公式サイト', 'https://www.asano.ed.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040402', 'school_website', '山手学院中学校・高等学校 公式サイト', 'https://www.yamate-gakuin.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040403', 'school_website', '神奈川大学附属中・高等学校 公式サイト', 'https://www.fhs.kanagawa-u.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040404', 'school_website', '慶應義塾普通部 公式サイト', 'https://www.kf.keio.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040405', 'school_website', '桐蔭学園中等教育学校 公式サイト', 'https://toin.ac.jp/ses/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040406', 'school_website', '桐光学園中学校・高等学校 公式サイト', 'https://www.toko.ed.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040407', 'school_website', '鎌倉学園中学校・高等学校 公式サイト', 'https://www.kamagaku.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040408', 'school_website', '慶應義塾湘南藤沢中等部・高等部 公式サイト', 'https://www.sfc-js.keio.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040409', 'school_website', '洗足学園中学校・高等学校 公式サイト', 'https://www.senzoku-gakuen.ed.jp/', 2026, 'copyrighted_quotable', '2026-05-04');
INSERT INTO jpms_sources (id, source_type, title, url, publication_year, rights_status, accessed_at) VALUES ('jpms_src_040410', 'school_website', '逗子開成中学校・高等学校 公式サイト', 'https://www.zushi-kaisei.ac.jp/', 2026, 'copyrighted_quotable', '2026-05-04');

-- Testimonial records
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000064', 'jpms_s_0122', 'principal', NULL, 0, 2025, 'school_website', '失敗をすることは必ずしも悪いことではありません。大切なのは、失敗をしても諦めずに、もう一度そこから学んで、挑戦をしていくことです。校訓「九転十起」の精神を通じて、努力することを評価し、諦めないこころを育てることが学校の使命です。', '校長による九転十起の精神と失敗からの学習重視に関するメッセージ', 'failure_resilience', 'positive', 'quoted_with_attribution', 'jpms_src_040401', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000065', 'jpms_s_0122', 'teacher', NULL, 0, 2025, 'school_website', '12歳から18歳までの6年間に出会い経験することが大切です。失敗は成長するためのチャンス。どんどん挑戦してほしい。', '教員による挑戦と経験の重要性についてのメッセージ', 'growth_mindset', 'positive', 'quoted_with_attribution', 'jpms_src_040401', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000066', 'jpms_s_0122', 'student_former', '102期卒業生', 1, 2025, 'school_website', '志の高い生徒が多く、多くの卒業生諸君が難関国公立大学・難関私立大学に合格しました。浅野での学びが進学実績に繋がっている。', '卒業生による進学実績と学びの質に関する証言', 'academic_achievement', 'positive', 'quoted_with_attribution', 'jpms_src_040401', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000067', 'jpms_s_0128', 'principal', NULL, 0, 2025, 'school_website', '「世界を舞台に活躍でき、世界に信頼される人間」を育成することを目的として、未来への夢をはぐくみ、その夢の実現をたくましくになっていく人を育てることを使命としています。', '山手学院の建学の精神と教育目標に関する校長メッセージ', 'global_education', 'positive', 'quoted_with_attribution', 'jpms_src_040402', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000068', 'jpms_s_0128', 'teacher', NULL, 0, 2025, 'school_website', '「Wise Freedom」—自らに誇りを持つとともに、他者の誇りと他者の自由を尊重する姿勢の上に成り立つ自由を育成します。これが本校「三本の柱」の中心です。', '教員による自由と責任に関する教育方針の説明', 'character_development', 'positive', 'quoted_with_attribution', 'jpms_src_040402', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000069', 'jpms_s_0128', 'student_current', '中学3年 女性', 1, 2025, 'school_website', '国内外の交流活動を通して異なる文化や値観に触れることで、グローバルな視野を育むことができた。自ら問いを立て、課題に挑戦する姿勢が身についた。', '在校生による国際交流と学習経験に関する声', 'international_experience', 'positive', 'anonymized_only', 'jpms_src_040402', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000070', 'jpms_s_0130', 'principal', NULL, 0, 2025, 'school_website', '人格・人権尊重の教育に根幹を置き、自主性の育成や自立の精神の涵養を主眼とした教育は変わらず、自由闊達で逞しい校風はずっと引き継がれています。多彩な他者と出会い、お互いを認め合いながら自らと違う価値観に触れ、自らを成長させることができる場所です。', '小林道夫校長による人格教育と自立精神に関するメッセージ', 'character_independence', 'positive', 'quoted_with_attribution', 'jpms_src_040403', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000071', 'jpms_s_0130', 'parent_current', '保護者', 1, 2025, 'school_website', '建学の精神「質実剛健」「積極進取」「中正堅実」を体現する人材育成方針が、実際の教育現場で実践されています。子どもが多彩なチャレンジの機会に恵まれています。', '保護者による教育方針の実践性に関する評価', 'educational_practice', 'positive', 'anonymized_only', 'jpms_src_040403', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000072', 'jpms_s_0130', 'student_former', '大学進学者', 1, 2025, 'school_website', '東大をはじめ難関大学への進学を実現できたのは、中高6年間の自主的学習の機会と、先生方の個別サポートのおかげです。創造的な学びで実践力を身につけることができました。', '卒業生による学習環境と進学実績に関する証言', 'academic_support', 'positive', 'quoted_with_attribution', 'jpms_src_040403', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000073', 'jpms_s_0133', 'principal', NULL, 0, 2025, 'school_website', '学びにおいてすべての教科を満遍なく修めることが大切です。乗り越えるべき壁を設定し、生徒たちに負荷をかけることで、彼らのポテンシャルを引き出し、力の発揮方法を学べるようにしています。', '普通部長・森上和哲による学習と挑戦に関するメッセージ', 'holistic_education', 'positive', 'quoted_with_attribution', 'jpms_src_040404', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000074', 'jpms_s_0133', 'teacher', NULL, 0, 2025, 'school_website', '高い品性と優れた知性を身につけ、自分の立てた大きな問いに答えることができる素地を作ることが教育目標です。友人との共通体験を通じた相互尊重と切磋琢磨の環境づくりを重視します。', '教員による品性と知性の育成方針', 'character_development', 'positive', 'quoted_with_attribution', 'jpms_src_040404', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000075', 'jpms_s_0133', 'student_current', '中学2年 男性', 1, 2025, 'school_website', 'めちゃくちゃ楽しい！みんなと仲良くできて部活も楽しいし、授業も面白い。友人との共通体験がこんなに大切なんだと気づきました。', '在校生による学校生活の充実に関する声', 'school_community', 'positive', 'anonymized_only', 'jpms_src_040404', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000076', 'jpms_s_0134', 'principal', NULL, 0, 2025, 'school_website', '子どもたちが大人が経験したことのない新しい世界を生きていくため、変化し続ける社会で生きるしなやかさとスキルを身につけさせることが重要です。知識や技能だけでなく、考える力・判断する力・表現する力を総合的に伸ばします。', '岡田直哉校長による変化対応能力と総合的育成に関するメッセージ', 'future_skills', 'positive', 'quoted_with_attribution', 'jpms_src_040405', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000077', 'jpms_s_0134', 'teacher', NULL, 0, 2025, 'school_website', 'アクティブラーニング型授業、探究、キャリア教育の「三本の柱」により、大学合格を人生の通過点として、次の社会を生き抜く力を身につける「新しい進学校」を実現しています。', '教員による教育理念の三本柱に関する説明', 'active_learning', 'positive', 'quoted_with_attribution', 'jpms_src_040405', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000078', 'jpms_s_0134', 'student_current', '中学1年 女性', 1, 2025, 'school_website', '授業時間を超えて放課後にも学習が続く楽しい時間として位置づけられている。探究の時間で自分の興味を深掘りでき、学力と人間性の両方が成長できていると感じます。', '在校生による探究学習への評価', 'inquiry_learning', 'positive', 'anonymized_only', 'jpms_src_040405', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000079', 'jpms_s_0135', 'principal', NULL, 0, 2025, 'school_website', '「世界に眼を開く」という建学の精神のもと、多様性を尊重し、個の可能性を最大限に引き出す教育に力を注いできました。変化の激しい時代にしなやかに対応し、確かな歩みを進める「次世代のリーダー」を育成することを使命としています。', '岡村薫校長による建学の精神と次世代リーダー育成に関するメッセージ', 'global_leadership', 'positive', 'quoted_with_attribution', 'jpms_src_040406', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000080', 'jpms_s_0135', 'teacher', NULL, 0, 2025, 'school_website', '現代社会は不確実性に満ち、将来の展望が見通しづらい時代です。だからこそ、自ら考え、行動し、他者と力を合わせて課題に立ち向かう姿勢が求められています。', '教員による時代適応力と協働性の育成に関する説明', 'future_readiness', 'positive', 'quoted_with_attribution', 'jpms_src_040406', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000081', 'jpms_s_0135', 'student_former', '大学進学者', 1, 2025, 'school_website', '多様性を尊重する校風の中で、異なる背景を持つ友人と出会うことで、自分の可能性の引き出し方を学びました。個性を尊重する教育が将来のキャリアに直結しています。', '卒業生による多様性尊重と個性育成に関する評価', 'diversity_inclusion', 'positive', 'quoted_with_attribution', 'jpms_src_040406', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000082', 'jpms_s_0137', 'principal', NULL, 0, 2025, 'school_website', '「質実剛健」「自主自律」を建学の精神として掲げています。「鎌倉武士のようにたくましい人間になってほしい」という思いと、「自分自身で物事を考えて、計画・立案・実行し、自分で自分自身を評価する」という思いを込めています。', '鎌倉学園の建学の精神「質実剛健」「自主自律」に関するメッセージ', 'character_autonomy', 'positive', 'quoted_with_attribution', 'jpms_src_040407', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000083', 'jpms_s_0137', 'teacher', NULL, 0, 2025, 'school_website', '校訓「礼義廉恥」は、節度を守ること、自分を実際以上に見せびらかさないこと、自分の過ちを隠さないこと、他人の悪事にひきずられないことを意味します。', '教員による校訓と倫理観の育成に関する説明', 'moral_development', 'positive', 'quoted_with_attribution', 'jpms_src_040407', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000084', 'jpms_s_0137', 'student_current', '中学3年 男性', 1, 2025, 'school_website', '文武両道の校風の中で、学業と部活動を両立させることで、たくましさと自主性が身につきました。鎌倉学園での経験が人間としての基盤になっていると感じます。', '在校生による文武両道と自主性に関する声', 'character_building', 'positive', 'anonymized_only', 'jpms_src_040407', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000085', 'jpms_s_0140', 'principal', NULL, 0, 2025, 'school_website', '慶應義塾の理念「独立自尊」「半学半教」に基づき、生徒が自ら学び、自ら考え、自ら実践する力を育成します。SFC独自の国際的な学習環境で、未来への視野を広げることを重視しています。', 'SFC部長による慶應理念と国際性に関するメッセージ', 'independent_learning', 'positive', 'quoted_with_attribution', 'jpms_src_040408', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000086', 'jpms_s_0140', 'teacher', NULL, 0, 2025, 'school_website', '生徒たちが自分たちの研究プロジェクトを主導し、実践的な学習を通じて問題解決能力を育成します。SFCの環境が創造的思考を引き出しています。', '教員による実践的学習と創造性育成に関する説明', 'practical_learning', 'positive', 'quoted_with_attribution', 'jpms_src_040408', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000087', 'jpms_s_0140', 'student_current', '高等部1年 女性', 1, 2025, 'school_website', '国際的な環境で多くの視点に触れることで、自分自身の考え方が柔軟になりました。SFCは自分らしく学べる場所です。', '在校生による国際環境と自己表現に関する声', 'international_learning', 'positive', 'anonymized_only', 'jpms_src_040408', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000088', 'jpms_s_0141', 'principal', NULL, 0, 2025, 'school_website', '洗足学園は光に満ち溢れた学び舎です。この環境で生徒たちは学びを深め、思索を深めます。うれしいことも悔しいことも、うまくいくことも失敗も、この場所に集った仲間と経験する中で、人間としての幸福な自己実現を実現してほしいです。', '宮阪元子校長による光と幸福な自己実現に関するメッセージ', 'happiness_realization', 'positive', 'quoted_with_attribution', 'jpms_src_040409', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000089', 'jpms_s_0141', 'parent_current', '保護者', 1, 2025, 'school_website', '親が思うように子どもは育たないことを学びました。親が見守ることの大切さを教えてくれる学校です。生徒ひとり一人の幸福な自己実現が教師全員の最大の願いだと感じられます。', '保護者による教育姿勢と見守り精神に関する評価', 'parental_trust', 'positive', 'anonymized_only', 'jpms_src_040409', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000090', 'jpms_s_0141', 'student_former', '大学進学者', 1, 2025, 'school_website', '東大20人合格の躍進を実現できたのは、再試文化と厳しさと優しさのバランスが取れた教育環境のおかげです。夢や希望を持ちながら自分らしく道を切り開く力が身につきました。', '卒業生による学習文化と夢実現に関する証言', 'academic_excellence', 'positive', 'quoted_with_attribution', 'jpms_src_040409', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000091', 'jpms_s_0145', 'principal', NULL, 0, 2025, 'school_website', '「開物成務」—人間性を開拓・啓発し、人としての務めをなすという建学の精神のもと、新しい時代を切り拓く人間を育てることが教育の原点です。生徒みんな良いものを持っているので、ぜひそれを型にはめずに伸ばしてあげたいです。', '小和田亥土校長による開物成務と個性尊重に関するメッセージ', 'individuality_respect', 'positive', 'quoted_with_attribution', 'jpms_src_040410', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000092', 'jpms_s_0145', 'teacher', NULL, 0, 2025, 'school_website', '独自の海洋教育、情操教育、コンピュータ教育、国際交流を通して、英語力の向上だけでなく広い視野を身につけさせることを目指しています。', '教員による多角的教育プログラムに関する説明', 'holistic_education', 'positive', 'quoted_with_attribution', 'jpms_src_040410', '2026-05-04');
INSERT INTO jpms_testimonials (id, school_id, speaker_category, speaker_name, speaker_anonymized, spoken_year, medium, excerpt, summary, theme, sentiment, rights_level, source_id, fetched_at) VALUES ('jpms_t_000093', 'jpms_s_0145', 'student_current', '中学2年 男性', 1, 2025, 'school_website', '海洋教育が将来のキャリアに新しい視点をもたらしました。個性を伸ばす環境の中で、自分が本当にやりたいことが見えてきました。逗子開成は型にはまらない教育が特徴です。', '在校生による個性育成と海洋教育に関する声', 'ocean_education', 'positive', 'anonymized_only', 'jpms_src_040410', '2026-05-04');
