-- JPMS-DB Phase 2.5 W40: 近畿圏（大阪・京都・兵庫・奈良・滋賀・和歌山）私立中学校
-- ID Range: jpms_s_0600 - jpms_s_0659
-- Source Range: jpms_src_050001 - jpms_src_050060
-- 既投入3校（灘中・洛南・神戸女学院）を除外
-- Total: 60 schools

-- Sources テーブル登録
INSERT INTO jpms_sources (id, source_type, title, author, url, accessed_at, publication_year, rights_status, primary_or_secondary, reliability_score, note) VALUES
('jpms_src_050001', 'school_website', '大阪星光学院中学校 公式サイト', '学校法人大阪星光学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050002', 'school_website', '清風南海中学校 公式サイト', '学校法人清風学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050003', 'school_website', '関西大倉中学校 公式サイト', '学校法人関西大倉学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050004', 'school_website', '大阪桐蔭中学校 公式サイト', '学校法人大阪桐蔭学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050005', 'school_website', '開明中学校 公式サイト', '学校法人開明学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050006', 'school_website', '四天王寺中学校 公式サイト', '学校法人四天王寺学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050007', 'school_website', '清教学園中学校 公式サイト', '学校法人清教学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050008', 'school_website', '明星中学校 公式サイト', '学校法人大阪明星学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050009', 'school_website', '初芝立命館中学校 公式サイト', '学校法人初芝学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050010', 'school_website', '関西大学第一中学校 公式サイト', '学校法人関西大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050011', 'school_website', '関西大学北陽中学校 公式サイト', '学校法人関西大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050012', 'school_website', '清風中学校 公式サイト', '学校法人清風学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050013', 'school_website', '上宮中学校 公式サイト', '学校法人上宮学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050014', 'school_website', '大谷中学校 公式サイト', '学校法人大谷学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050015', 'school_website', '城星学園中学校 公式サイト', '学校法人城星学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050016', 'school_website', '追手門学院中学校 公式サイト', '学校法人追手門学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050017', 'school_website', '近畿大学附属中学校 公式サイト', '学校法人近畿大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050018', 'school_website', 'PL学園中学校 公式サイト', '宗教法人パーフェクトリバティー教団', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050019', 'school_website', '桃山学院中学校 公式サイト', '学校法人桃山学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050020', 'school_website', '大阪薫英女学院中学校 公式サイト', '学校法人大阪薫英女学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050021', 'school_website', '相愛中学校 公式サイト', '学校法人相愛学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050022', 'school_website', '香里ヌヴェール学園中学校 公式サイト', '学校法人香里ヌヴェール学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050023', 'school_website', '同志社中学校 公式サイト', '学校法人同志社', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050024', 'school_website', '立命館中学校 公式サイト', '学校法人立命館', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050025', 'school_website', '京都女子中学校 公式サイト', '学校法人京都女子大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050026', 'school_website', '平安女学院中学校 公式サイト', '学校法人平安女学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050027', 'school_website', '京都聖母学院中学校 公式サイト', '学校法人京都聖母学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050028', 'school_website', 'ノートルダム女学院中学校 公式サイト', '学校法人ノートルダム女学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050029', 'school_website', '東山中学校 公式サイト', '学校法人浄土宗東山学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050030', 'school_website', '京都産業大学附属中学校 公式サイト', '学校法人京都産業大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050031', 'school_website', '洛星中学校 公式サイト', '学校法人ビアトル学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050032', 'school_website', '甲陽学院中学校 公式サイト', '学校法人甲陽学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050033', 'school_website', '白陵中学校 公式サイト', '学校法人白陵学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050034', 'school_website', '六甲学院中学校 公式サイト', '学校法人六甲学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050035', 'school_website', '甲南中学校 公式サイト', '学校法人甲南学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050036', 'school_website', '関西学院中学部 公式サイト', '学校法人関西学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050037', 'school_website', '神戸海星女子学院中学校 公式サイト', '学校法人神戸海星女子学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050038', 'school_website', '親和中学校 公式サイト', '学校法人親和学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050039', 'school_website', '武庫川女子大学附属中学校 公式サイト', '学校法人武庫川女子大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050040', 'school_website', '雲雀丘学園中学校 公式サイト', '学校法人雲雀丘学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050041', 'school_website', '滝川中学校 公式サイト', '学校法人滝川学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050042', 'school_website', '滝川第二中学校 公式サイト', '学校法人滝川学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050043', 'school_website', '淳心学院中学校 公式サイト', '学校法人淳心学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050044', 'school_website', '神戸国際中等教育学校 公式サイト', '学校法人神戸国際', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050045', 'school_website', '報徳学園中学校 公式サイト', '学校法人報徳学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050046', 'school_website', '夙川学院中学校 公式サイト', '学校法人夙川学院', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050047', 'school_website', '東大寺学園中学校 公式サイト', '学校法人東大寺学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050048', 'school_website', '西大和学園中学校 公式サイト', '学校法人西大和学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050049', 'school_website', '奈良学園中学校 公式サイト', '学校法人奈良学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050050', 'school_website', '帝塚山中学校 公式サイト', '学校法人帝塚山学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050051', 'school_website', '聖心学園中学校 公式サイト', '学校法人聖心学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050052', 'school_website', '智辯学園中学校 公式サイト', '学校法人智辯学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050053', 'school_website', '智辯学園奈良カレッジ中学校 公式サイト', '学校法人智辯学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050054', 'school_website', '立命館守山中学校 公式サイト', '学校法人立命館', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050055', 'school_website', '比叡山中学校 公式サイト', '学校法人比叡山学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050056', 'school_website', '近江兄弟社中学校 公式サイト', '学校法人ヴォーリズ学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050057', 'school_website', '滋賀学園中学校 公式サイト', '学校法人滋賀学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050058', 'school_website', '智辯学園和歌山中学校 公式サイト', '学校法人智辯学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050059', 'school_website', '開智中学校 公式サイト', '学校法人開智学園', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定'),
('jpms_src_050060', 'school_website', '近畿大学附属和歌山中学校 公式サイト', '学校法人近畿大学', NULL, datetime('now'), NULL, 'copyrighted_permission_required', 'primary', 95, 'Phase 2で実URL取得予定');

-- Schools テーブル登録
-- Osaka: 22 schools (jpms_s_0600 - jpms_s_0621)
INSERT INTO jpms_schools (id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, primary_source_id, data_completeness, status) VALUES
('jpms_s_0600', '大阪星光学院中学校', 'おおさかせいこうがくいんちゅうがっこう', 1958, '学校法人大阪星光学院', 'catholic', 'boys', 'attached', '大阪府', '大阪市', 'jpms_src_050001', 30, 'active'),
('jpms_s_0601', '清風南海中学校', 'せいふうなんかいちゅうがっこう', 1972, '学校法人清風学園', 'non_religious', 'boys', 'attached', '大阪府', 'その他', 'jpms_src_050002', 30, 'active'),
('jpms_s_0602', '関西大倉中学校', 'かんさいおおくらちゅうがっこう', 1985, '学校法人関西大倉学園', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050003', 30, 'active'),
('jpms_s_0603', '大阪桐蔭中学校', 'おおさかきりえんちゅうがっこう', 2007, '学校法人大阪桐蔭学園', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050004', 30, 'active'),
('jpms_s_0604', '開明中学校', 'かいめいちゅうがっこう', 1903, '学校法人開明学園', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050005', 30, 'active'),
('jpms_s_0605', '四天王寺中学校', 'してんのうじちゅうがっこう', 1964, '学校法人四天王寺学園', 'buddhist', 'girls', 'attached', '大阪府', 'その他', 'jpms_src_050006', 30, 'active'),
('jpms_s_0606', '清教学園中学校', 'せいきょうがくえんちゅうがっこう', 1947, '学校法人清教学園', 'protestant', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050007', 30, 'active'),
('jpms_s_0607', '明星中学校', 'めいせいちゅうがっこう', 1951, '学校法人大阪明星学園', 'catholic', 'boys', 'attached', '大阪府', 'その他', 'jpms_src_050008', 30, 'active'),
('jpms_s_0608', '初芝立命館中学校', 'しょしばりつめいかんちゅうがっこう', 1989, '学校法人初芝学園', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050009', 30, 'active'),
('jpms_s_0609', '関西大学第一中学校', 'かんさいだいがくだいいちちゅうがっこう', 1905, '学校法人関西大学', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050010', 30, 'active'),
('jpms_s_0610', '関西大学北陽中学校', 'かんさいだいがくほくようちゅうがっこう', 1950, '学校法人関西大学', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050011', 30, 'active'),
('jpms_s_0611', '清風中学校', 'せいふうちゅうがっこう', 1935, '学校法人清風学園', 'non_religious', 'boys', 'attached', '大阪府', 'その他', 'jpms_src_050012', 30, 'active'),
('jpms_s_0612', '上宮中学校', 'こうみやちゅうがっこう', 1969, '学校法人上宮学園', 'buddhist', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050013', 30, 'active'),
('jpms_s_0613', '大谷中学校', 'おおたにちゅうがっこう', 2004, '学校法人大谷学園', 'buddhist', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050014', 30, 'active'),
('jpms_s_0614', '城星学園中学校', 'じょうせいがくえんちゅうがっこう', 1882, '学校法人城星学園', 'catholic', 'girls', 'attached', '大阪府', 'その他', 'jpms_src_050015', 30, 'active'),
('jpms_s_0615', '追手門学院中学校', 'おいてもんがくいんちゅうがっこう', 1888, '学校法人追手門学院', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050016', 30, 'active'),
('jpms_s_0616', '近畿大学附属中学校', 'きんきだいがくふぞくちゅうがっこう', 1968, '学校法人近畿大学', 'non_religious', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050017', 30, 'active'),
('jpms_s_0617', 'PL学園中学校', 'ぴーえるがくえんちゅうがっこう', 1923, '宗教法人パーフェクトリバティー教団', 'other', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050018', 30, 'active'),
('jpms_s_0618', '桃山学院中学校', 'ももやまがくいんちゅうがっこう', 1884, '学校法人桃山学院', 'anglican', 'coed', 'attached', '大阪府', 'その他', 'jpms_src_050019', 30, 'active'),
('jpms_s_0619', '大阪薫英女学院中学校', 'おおさかくんえいじょがくいんちゅうがっこう', 1897, '学校法人大阪薫英女学院', 'non_religious', 'girls', 'attached', '大阪府', 'その他', 'jpms_src_050020', 30, 'active'),
('jpms_s_0620', '相愛中学校', 'そうあいちゅうがっこう', 1902, '学校法人相愛学園', 'buddhist', 'girls', 'attached', '大阪府', 'その他', 'jpms_src_050021', 30, 'active'),
('jpms_s_0621', '香里ヌヴェール学園中学校', 'こうりぬゔぇーるがくえんちゅうがっこう', 1955, '学校法人香里ヌヴェール学園', 'catholic', 'girls', 'attached', '大阪府', 'その他', 'jpms_src_050022', 30, 'active'),
-- Kyoto: 9 schools (jpms_s_0622 - jpms_s_0630)
('jpms_s_0622', '同志社中学校', 'どうししゃちゅうがっこう', 1876, '学校法人同志社', 'protestant', 'boys', 'attached', '京都府', '京都市', 'jpms_src_050023', 30, 'active'),
('jpms_s_0623', '立命館中学校', 'りつめいかんちゅうがっこう', 1913, '学校法人立命館', 'non_religious', 'coed', 'attached', '京都府', '京都市', 'jpms_src_050024', 30, 'active'),
('jpms_s_0624', '京都女子中学校', 'きょうとじょしちゅうがっこう', 1903, '学校法人京都女子大学', 'buddhist', 'girls', 'attached', '京都府', '京都市', 'jpms_src_050025', 30, 'active'),
('jpms_s_0625', '平安女学院中学校', 'へいあんじょがくいんちゅうがっこう', 1879, '学校法人平安女学院', 'protestant', 'girls', 'attached', '京都府', '京都市', 'jpms_src_050026', 30, 'active'),
('jpms_s_0626', '京都聖母学院中学校', 'きょうとせいぼがくいんちゅうがっこう', 1904, '学校法人京都聖母学院', 'catholic', 'girls', 'attached', '京都府', '京都市', 'jpms_src_050027', 30, 'active'),
('jpms_s_0627', 'ノートルダム女学院中学校', 'のーとるだむじょがくいんちゅうがっこう', 1956, '学校法人ノートルダム女学院', 'catholic', 'girls', 'attached', '京都府', '京都市', 'jpms_src_050028', 30, 'active'),
('jpms_s_0628', '東山中学校', 'ひがしやまちゅうがっこう', 1991, '学校法人浄土宗東山学園', 'buddhist', 'boys', 'attached', '京都府', '京都市', 'jpms_src_050029', 30, 'active'),
('jpms_s_0629', '京都産業大学附属中学校', 'きょうとさんぎょうだいがくふぞくちゅうがっこう', 1965, '学校法人京都産業大学', 'non_religious', 'coed', 'attached', '京都府', '京都市', 'jpms_src_050030', 30, 'active'),
('jpms_s_0630', '洛星中学校', 'らくせいちゅうがっこう', 1952, '学校法人ビアトル学園', 'catholic', 'boys', 'attached', '京都府', '京都市', 'jpms_src_050031', 30, 'active'),
-- Hyogo: 15 schools (jpms_s_0631 - jpms_s_0645)
('jpms_s_0631', '甲陽学院中学校', 'こうようがくいんちゅうがっこう', 1962, '学校法人甲陽学院', 'non_religious', 'boys', 'attached', '兵庫県', 'その他', 'jpms_src_050032', 30, 'active'),
('jpms_s_0632', '白陵中学校', 'はくりょうちゅうがっこう', 1981, '学校法人白陵学園', 'non_religious', 'boys', 'attached', '兵庫県', 'その他', 'jpms_src_050033', 30, 'active'),
('jpms_s_0633', '六甲学院中学校', 'ろっこうがくいんちゅうがっこう', 1952, '学校法人六甲学院', 'catholic', 'boys', 'attached', '兵庫県', '神戸市', 'jpms_src_050034', 30, 'active'),
('jpms_s_0634', '甲南中学校', 'こうなんちゅうがっこう', 1917, '学校法人甲南学園', 'non_religious', 'boys', 'attached', '兵庫県', '神戸市', 'jpms_src_050035', 30, 'active'),
('jpms_s_0635', '関西学院中学部', 'かんさいがくいんちゅうがくぶ', 1889, '学校法人関西学院', 'protestant', 'coed', 'attached', '兵庫県', 'その他', 'jpms_src_050036', 30, 'active'),
('jpms_s_0636', '神戸海星女子学院中学校', 'こうべかいせいじょしがくいんちゅうがっこう', 1950, '学校法人神戸海星女子学院', 'catholic', 'girls', 'attached', '兵庫県', '神戸市', 'jpms_src_050037', 30, 'active'),
('jpms_s_0637', '親和中学校', 'しんわちゅうがっこう', 1880, '学校法人親和学園', 'protestant', 'girls', 'attached', '兵庫県', '神戸市', 'jpms_src_050038', 30, 'active'),
('jpms_s_0638', '武庫川女子大学附属中学校', 'むこがわじょしだいがくふぞくちゅうがっこう', 1961, '学校法人武庫川女子大学', 'non_religious', 'girls', 'attached', '兵庫県', 'その他', 'jpms_src_050039', 30, 'active'),
('jpms_s_0639', '雲雀丘学園中学校', 'ひばりがおかがくえんちゅうがっこう', 1984, '学校法人雲雀丘学園', 'non_religious', 'coed', 'attached', '兵庫県', 'その他', 'jpms_src_050040', 30, 'active'),
('jpms_s_0640', '滝川中学校', 'たきがわちゅうがっこう', 1927, '学校法人滝川学園', 'non_religious', 'boys', 'attached', '兵庫県', '神戸市', 'jpms_src_050041', 30, 'active'),
('jpms_s_0641', '滝川第二中学校', 'たきがわだいにちゅうがっこう', 1998, '学校法人滝川学園', 'non_religious', 'coed', 'attached', '兵庫県', 'その他', 'jpms_src_050042', 30, 'active'),
('jpms_s_0642', '淳心学院中学校', 'じゅんしんがくいんちゅうがっこう', 1962, '学校法人淳心学院', 'catholic', 'boys', 'attached', '兵庫県', 'その他', 'jpms_src_050043', 30, 'active'),
('jpms_s_0643', '神戸国際中等教育学校', 'こうべこくさいちゅうとうきょういくがっこう', 2002, '学校法人神戸国際', 'non_religious', 'coed', 'full', '兵庫県', '神戸市', 'jpms_src_050044', 30, 'active'),
('jpms_s_0644', '報徳学園中学校', 'ほうとくがくえんちゅうがっこう', 1949, '学校法人報徳学園', 'non_religious', 'boys', 'attached', '兵庫県', 'その他', 'jpms_src_050045', 30, 'active'),
('jpms_s_0645', '夙川学院中学校', 'しゅくがわがくいんちゅうがっこう', 1895, '学校法人夙川学院', 'other', 'girls', 'attached', '兵庫県', 'その他', 'jpms_src_050046', 30, 'active'),
-- Nara: 7 schools (jpms_s_0646 - jpms_s_0652)
('jpms_s_0646', '東大寺学園中学校', 'とうだいじがくえんちゅうがっこう', 1965, '学校法人東大寺学園', 'buddhist', 'boys', 'attached', '奈良県', '奈良市', 'jpms_src_050047', 30, 'active'),
('jpms_s_0647', '西大和学園中学校', 'にしやまとがくえんちゅうがっこう', 1986, '学校法人西大和学園', 'non_religious', 'coed', 'attached', '奈良県', 'その他', 'jpms_src_050048', 30, 'active'),
('jpms_s_0648', '奈良学園中学校', 'ならがくえんちゅうがっこう', 1927, '学校法人奈良学園', 'non_religious', 'coed', 'attached', '奈良県', '奈良市', 'jpms_src_050049', 30, 'active'),
('jpms_s_0649', '帝塚山中学校', 'てづかやまちゅうがっこう', 1971, '学校法人帝塚山学園', 'non_religious', 'girls', 'attached', '奈良県', '奈良市', 'jpms_src_050050', 30, 'active'),
('jpms_s_0650', '聖心学園中学校', 'せいしんがくえんちゅうがっこう', 1957, '学校法人聖心学園', 'catholic', 'girls', 'attached', '奈良県', '奈良市', 'jpms_src_050051', 30, 'active'),
('jpms_s_0651', '智辯学園中学校', 'ちべんがくえんちゅうがっこう', 1969, '学校法人智辯学園', 'buddhist', 'coed', 'attached', '奈良県', '奈良市', 'jpms_src_050052', 30, 'active'),
('jpms_s_0652', '智辯学園奈良カレッジ中学校', 'ちべんがくえんならかれっじちゅうがっこう', 1998, '学校法人智辯学園', 'buddhist', 'coed', 'attached', '奈良県', '奈良市', 'jpms_src_050053', 30, 'active'),
-- Shiga: 4 schools (jpms_s_0653 - jpms_s_0656)
('jpms_s_0653', '立命館守山中学校', 'りつめいかんもりやまちゅうがっこう', 1979, '学校法人立命館', 'non_religious', 'coed', 'attached', '滋賀県', 'その他', 'jpms_src_050054', 30, 'active'),
('jpms_s_0654', '比叡山中学校', 'ひえいざんちゅうがっこう', 1947, '学校法人比叡山学園', 'buddhist', 'coed', 'attached', '滋賀県', 'その他', 'jpms_src_050055', 30, 'active'),
('jpms_s_0655', '近江兄弟社中学校', 'おうみきょうだいしゃちゅうがっこう', 1910, '学校法人ヴォーリズ学園', 'protestant', 'coed', 'attached', '滋賀県', 'その他', 'jpms_src_050056', 30, 'active'),
('jpms_s_0656', '滋賀学園中学校', 'しががくえんちゅうがっこう', 1989, '学校法人滋賀学園', 'non_religious', 'coed', 'attached', '滋賀県', 'その他', 'jpms_src_050057', 30, 'active'),
-- Wakayama: 3 schools (jpms_s_0657 - jpms_s_0659)
('jpms_s_0657', '智辯学園和歌山中学校', 'ちべんがくえんわかやまちゅうがっこう', 1975, '学校法人智辯学園', 'buddhist', 'coed', 'attached', '和歌山県', 'その他', 'jpms_src_050058', 30, 'active'),
('jpms_s_0658', '開智中学校', 'かいちちゅうがっこう', 1997, '学校法人開智学園', 'non_religious', 'coed', 'attached', '和歌山県', 'その他', 'jpms_src_050059', 30, 'active'),
('jpms_s_0659', '近畿大学附属和歌山中学校', 'きんきだいがくふぞくわかやまちゅうがっこう', 1992, '学校法人近畿大学', 'non_religious', 'coed', 'attached', '和歌山県', 'その他', 'jpms_src_050060', 30, 'active');

