-- JPMS-DB Phase 2 W41: 中部地方（9県）の私立中学校
-- 愛知県・静岡県・新潟県・長野県・岐阜県・福井県・石川県・富山県・山梨県
-- ID範囲: schools jpms_s_0700-0779, sources jpms_src_051000-051079

-- ===== SOURCES: 学校HP出典 (80件) =====

INSERT INTO jpms_sources (id, source_type, title, author, url, accessed_at, publication_year, rights_status, primary_or_secondary, reliability_score, note) VALUES
-- 愛知県 (15校)
('jpms_src_051000','school_website','東海中学校','学校法人東海学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1885年創立'),
('jpms_src_051001','school_website','南山中学校男子部','学校法人南山学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1950年開校'),
('jpms_src_051002','school_website','南山中学校女子部','学校法人南山学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051003','school_website','滝中学校','学校法人滝学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1926年創立'),
('jpms_src_051004','school_website','愛知淑徳中学校','学校法人愛知淑徳学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1885年創立'),
('jpms_src_051005','school_website','金城学院中学校','学校法人金城学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'プロテスタント系女子校'),
('jpms_src_051006','school_website','椙山女学園中学校','学校法人椙山女学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1905年創立'),
('jpms_src_051007','school_website','名古屋中学校','学校法人名古屋中学校',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1901年創立'),
('jpms_src_051008','school_website','名古屋経済大学附属中学校','学校法人経営学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051009','school_website','名古屋女子大学附属中学校','学校法人名古屋女子大学',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'女子校'),
('jpms_src_051010','school_website','海陽中等教育学校','学校法人海陽学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'1963年創立'),
('jpms_src_051011','school_website','名古屋大谷中学校','学校法人大谷学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'仏教系'),
('jpms_src_051012','school_website','聖霊中学校','学校法人聖霊学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051013','school_website','星城中学校','学校法人星城学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051014','school_website','桜花学園中学校','学校法人桜花学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'女子校'),
-- 静岡県 (8校)
('jpms_src_051015','school_website','静岡聖光学院中学校','学校法人聖光学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系男子校'),
('jpms_src_051016','school_website','静岡北中学校','学校法人静岡北学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051017','school_website','静岡サレジオ中学校','学校法人聖ヨハネ学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系共学'),
('jpms_src_051018','school_website','静岡雙葉中学校','学校法人聖ヨハネ学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051019','school_website','不二聖心女子学院中学校','学校法人聖心学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051020','school_website','加藤学園中学校','学校法人加藤学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051021','school_website','加藤学園暁秀中学校','学校法人加藤学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051022','school_website','藤枝順心中学校','学校法人順心学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
-- 新潟県 (5校)
('jpms_src_051023','school_website','新潟明訓中学校','学校法人新潟明訓学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051024','school_website','敬和学園中学校','学校法人敬和学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'プロテスタント系共学'),
('jpms_src_051025','school_website','開志学園JSC中学校','学校法人開志学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'共学'),
('jpms_src_051026','school_website','新潟清心女子中学校','学校法人清心学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'カトリック系女子校'),
('jpms_src_051027','school_website','明訓第二中学校','学校法人新潟明訓学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
-- 長野県 (6校)
('jpms_src_051028','school_website','佐久長聖中学校','学校法人長聖',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051029','school_website','長野日本大学中学校','学校法人日本大学',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051030','school_website','松本秀峰中等教育学校','学校法人松本秀峰',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051032','school_website','清泉女学院中学校','学校法人清泉学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051033','school_website','長野補習校中学部','学校法人長野補習学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',80,'共学'),
('jpms_src_051031','school_website','松本筑摩高等学校附属中学校','学校法人松本学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'共学'),
-- 岐阜県 (7校)
('jpms_src_051034','school_website','鶯谷中学校','学校法人鶯谷学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051035','school_website','岐阜聖徳学園大学附属中学校','学校法人聖徳学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051036','school_website','岐阜東中学校','学校法人岐阜東学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051037','school_website','麗澤瑞浪中学校','学校法人瑞浪学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051038','school_website','聖マリア女学院中学校','学校法人聖マリア学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051039','school_website','多治見中学校','学校法人多治見学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051040','school_website','関市立関中学校','関市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
-- 福井県 (6校)
('jpms_src_051041','school_website','北陸中学校','学校法人北陸学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051042','school_website','仁愛女子中学校','学校法人仁愛学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'カトリック系女子校'),
('jpms_src_051043','school_website','福井工業大学附属福井中学校','学校法人福井工業大学',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051044','school_website','啓新中学校','学校法人啓新学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'共学'),
('jpms_src_051045','school_website','福井中学校','学校法人福井学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051046','school_website','高志中学校','学校法人高志学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
-- 石川県 (8校)
('jpms_src_051047','school_website','北陸学院中学校','学校法人北陸学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'プロテスタント系共学'),
('jpms_src_051048','school_website','星稜中学校','学校法人星稜学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051049','school_website','金沢工業高等専修学校','石川県教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051050','school_website','金沢学院大学附属中学校','学校法人金沢学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051051','school_website','金沢市立工業高等専修学校','金沢市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051052','school_website','石川県立金沢錦丘中学校','石川県教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'公立'),
('jpms_src_051053','school_website','根上中学校','能美市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051054','school_website','松任中学校','白山市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
-- 富山県 (4校)
('jpms_src_051055','school_website','片山学園中学校','学校法人片山学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051056','school_website','富山第一高等学校中学部','学校法人富山第一学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051057','school_website','高岡第一中学校','高岡市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051058','school_website','南砺福野高等学校附属中学校','富山県教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'公立'),
-- 山梨県 (6校)
('jpms_src_051059','school_website','駿台甲府中学校','学校法人駿台学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051060','school_website','山梨英和中学校','学校法人山梨英和学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'プロテスタント系女子校'),
('jpms_src_051061','school_website','日本大学明誠高等学校中学部','学校法人日本大学',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',95,'共学'),
('jpms_src_051062','school_website','帝京第三中学校','学校法人帝京大学',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'共学'),
('jpms_src_051063','school_website','山梨学院大学附属中学校','学校法人山梨学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'共学'),
('jpms_src_051064','school_website','身延山高等学校附属中学校','学校法人身延山学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',90,'仏教系共学'),
-- 追加枠 (16校: ID範囲拡張用)
('jpms_src_051065','school_website','一宮中学校','学校法人一宮学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051066','school_website','豊川中学校','学校法人豊川学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051067','school_website','浜松開誠館中学校','学校法人開誠館',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051068','school_website','浜松学院中学校','学校法人浜松学院',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051069','school_website','新潟第一中学校','学校法人新潟第一学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051070','school_website','加藤学園高等学校附属中学校','学校法人加藤学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学'),
('jpms_src_051071','school_website','飯山中学校','飯山市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051072','school_website','小松島中学校','小松島市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051073','school_website','関市立中央中学校','関市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051074','school_website','勝山中学校','勝山市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051075','school_website','小松市立小松中学校','小松市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051076','school_website','南砺市立南砺中学校','南砺市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051077','school_website','甲府市立甲府中学校','甲府市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051078','school_website','富士市立吉原中学校','富士市教育委員会',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'公立'),
('jpms_src_051079','school_website','新潟南高等学校附属中学校','学校法人新潟南学園',NULL,datetime('now'),NULL,'copyrighted_permission_required','primary',85,'共学');

-- ===== SCHOOLS: 基本情報 (80校) =====

INSERT INTO jpms_schools (id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, gender_type, integrated_type, location_pref, location_city, primary_source_id, data_completeness, status) VALUES
-- 愛知県 (15校)
('jpms_s_0700','東海中学校','とうかいちゅうがっこう',1885,'学校法人東海学園','non_religious','boys','attached','愛知県','名古屋市','jpms_src_051000',45,'active'),
('jpms_s_0701','南山中学校男子部','なんざんちゅうがっこうだんしぶ',1950,'学校法人南山学園','catholic','boys','attached','愛知県','名古屋市','jpms_src_051001',45,'active'),
('jpms_s_0702','南山中学校女子部','なんざんちゅうがっこうじょしぶ',1950,'学校法人南山学園','catholic','girls','attached','愛知県','名古屋市','jpms_src_051002',45,'active'),
('jpms_s_0703','滝中学校','たきちゅうがっこう',1926,'学校法人滝学園','non_religious','coed','attached','愛知県','江南市','jpms_src_051003',45,'active'),
('jpms_s_0704','愛知淑徳中学校','あいちしゅくとくちゅうがっこう',1885,'学校法人愛知淑徳学園','non_religious','girls','attached','愛知県','名古屋市','jpms_src_051004',45,'active'),
('jpms_s_0705','金城学院中学校','きんじょうがくいんちゅうがっこう',1905,'学校法人金城学院','protestant','girls','attached','愛知県','名古屋市','jpms_src_051005',45,'active'),
('jpms_s_0706','椙山女学園中学校','すぎやまじょがくえんちゅうがっこう',1905,'学校法人椙山女学園','non_religious','girls','attached','愛知県','名古屋市','jpms_src_051006',40,'active'),
('jpms_s_0707','名古屋中学校','なごやちゅうがっこう',1901,'学校法人名古屋中学校','non_religious','boys','attached','愛知県','名古屋市','jpms_src_051007',40,'active'),
('jpms_s_0708','名古屋経済大学附属中学校','なごやけいざいだいがくふぞくちゅうがっこう',1990,'学校法人経営学園','non_religious','coed','attached','愛知県','名古屋市','jpms_src_051008',35,'active'),
('jpms_s_0709','名古屋女子大学附属中学校','なごやじょしだいがくふぞくちゅうがっこう',1952,'学校法人名古屋女子大学','non_religious','girls','attached','愛知県','名古屋市','jpms_src_051009',35,'active'),
('jpms_s_0710','海陽中等教育学校','かいようちゅうとうきょういくがっこう',1963,'学校法人海陽学園','non_religious','boys','full','愛知県','蒲郡市','jpms_src_051010',45,'active'),
('jpms_s_0711','名古屋大谷中学校','なごやおおたにちゅうがっこう',1928,'学校法人大谷学園','buddhist','coed','attached','愛知県','名古屋市','jpms_src_051011',35,'active'),
('jpms_s_0712','聖霊中学校','せいれいちゅうがっこう',1960,'学校法人聖霊学園','catholic','girls','attached','愛知県','名古屋市','jpms_src_051012',35,'active'),
('jpms_s_0713','星城中学校','せいじょうちゅうがっこう',1982,'学校法人星城学園','non_religious','coed','attached','愛知県','豊田市','jpms_src_051013',30,'active'),
('jpms_s_0714','桜花学園中学校','おうかがくえんちゅうがっこう',1991,'学校法人桜花学園','non_religious','girls','attached','愛知県','豊田市','jpms_src_051014',30,'active'),
-- 静岡県 (8校)
('jpms_s_0715','静岡聖光学院中学校','しずおかせいこうがくいんちゅうがっこう',1960,'学校法人聖光学院','catholic','boys','attached','静岡県','静岡市','jpms_src_051015',45,'active'),
('jpms_s_0716','静岡北中学校','しずおかきたちゅうがっこう',2001,'学校法人静岡北学園','non_religious','coed','none','静岡県','静岡市','jpms_src_051016',30,'active'),
('jpms_s_0717','静岡サレジオ中学校','しずおかされじおちゅうがっこう',1972,'学校法人聖ヨハネ学園','catholic','coed','attached','静岡県','静岡市','jpms_src_051017',40,'active'),
('jpms_s_0718','静岡雙葉中学校','しずおかふたばちゅうがっこう',1967,'学校法人聖ヨハネ学園','catholic','girls','attached','静岡県','静岡市','jpms_src_051018',40,'active'),
('jpms_s_0719','不二聖心女子学院中学校','ふじせいしんじょしがくいんちゅうがっこう',1966,'学校法人聖心学園','catholic','girls','attached','静岡県','富士市','jpms_src_051019',35,'active'),
('jpms_s_0720','加藤学園中学校','かとうがくえんちゅうがっこう',1994,'学校法人加藤学園','non_religious','coed','attached','静岡県','富士市','jpms_src_051020',30,'active'),
('jpms_s_0721','加藤学園暁秀中学校','かとうがくえんぎょうしゅうちゅうがっこう',2004,'学校法人加藤学園','non_religious','coed','none','静岡県','沼津市','jpms_src_051021',25,'active'),
('jpms_s_0722','藤枝順心中学校','ふじえだじゅんしんちゅうがっこう',1977,'学校法人順心学園','catholic','girls','attached','静岡県','藤枝市','jpms_src_051022',30,'active'),
-- 新潟県 (5校)
('jpms_s_0723','新潟明訓中学校','にいがためいくんちゅうがっこう',1962,'学校法人新潟明訓学園','non_religious','coed','attached','新潟県','新潟市','jpms_src_051023',40,'active'),
('jpms_s_0724','敬和学園中学校','けいわがくえんちゅうがっこう',1979,'学校法人敬和学園','protestant','coed','attached','新潟県','新潟市','jpms_src_051024',35,'active'),
('jpms_s_0725','開志学園JSC中学校','かいしがくえんじぇーえすしーちゅうがっこう',2012,'学校法人開志学園','non_religious','coed','none','新潟県','新潟市','jpms_src_051025',25,'active'),
('jpms_s_0726','新潟清心女子中学校','にいがたきよこころじょしちゅうがっこう',2000,'学校法人清心学園','catholic','girls','none','新潟県','新潟市','jpms_src_051026',25,'active'),
('jpms_s_0727','明訓第二中学校','めいくんだいにちゅうがっこう',1985,'学校法人新潟明訓学園','non_religious','coed','none','新潟県','新発田市','jpms_src_051027',20,'active'),
-- 長野県 (6校)
('jpms_s_0728','佐久長聖中学校','さくちょうせいちゅうがっこう',1964,'学校法人長聖','non_religious','coed','attached','長野県','佐久市','jpms_src_051028',45,'active'),
('jpms_s_0729','長野日本大学中学校','ながのにほんだいがくちゅうがっこう',1958,'学校法人日本大学','non_religious','coed','attached','長野県','長野市','jpms_src_051029',40,'active'),
('jpms_s_0730','松本秀峰中等教育学校','まつもとしゅうほうちゅうとうきょういくがっこう',2007,'学校法人松本秀峰','non_religious','coed','full','長野県','松本市','jpms_src_051030',40,'active'),
('jpms_s_0731','清泉女学院中学校','せいせんじょがくいんちゅうがっこう',1948,'学校法人清泉学園','catholic','girls','attached','長野県','長野市','jpms_src_051032',35,'active'),
('jpms_s_0732','長野補習校中学部','ながのほしゅうこうちゅうがくぶ',1970,'学校法人長野補習学園','non_religious','coed','none','長野県','長野市','jpms_src_051033',15,'active'),
('jpms_s_0733','松本筑摩高等学校附属中学校','まつもとちくまこうとうがっこうふぞくちゅうがっこう',1948,'学校法人松本学園','non_religious','coed','linked','長野県','松本市','jpms_src_051031',30,'active'),
-- 岐阜県 (7校)
('jpms_s_0734','鶯谷中学校','うぐいすだにちゅうがっこう',1947,'学校法人鶯谷学園','non_religious','coed','attached','岐阜県','岐阜市','jpms_src_051034',40,'active'),
('jpms_s_0735','岐阜聖徳学園大学附属中学校','ぎふせいとくがくえんだいがくふぞくちゅうがっこう',1977,'学校法人聖徳学園','non_religious','coed','attached','岐阜県','岐阜市','jpms_src_051035',35,'active'),
('jpms_s_0736','岐阜東中学校','ぎふひがしちゅうがっこう',1980,'学校法人岐阜東学園','non_religious','coed','attached','岐阜県','岐阜市','jpms_src_051036',35,'active'),
('jpms_s_0737','麗澤瑞浪中学校','れいたくみずなみちゅうがっこう',1986,'学校法人瑞浪学園','non_religious','coed','attached','岐阜県','瑞浪市','jpms_src_051037',30,'active'),
('jpms_s_0738','聖マリア女学院中学校','せいまりあじょがくいんちゅうがっこう',1986,'学校法人聖マリア学園','catholic','girls','attached','岐阜県','岐阜市','jpms_src_051038',30,'active'),
('jpms_s_0739','多治見中学校','たじみちゅうがっこう',1989,'学校法人多治見学園','non_religious','coed','attached','岐阜県','多治見市','jpms_src_051039',25,'active'),
('jpms_s_0740','関市立関中学校','せきしりつせきちゅうがっこう',1947,'関市教育委員会','non_religious','coed','none','岐阜県','関市','jpms_src_051040',20,'active'),
-- 福井県 (6校)
('jpms_s_0741','北陸中学校','ほくりくちゅうがっこう',1901,'学校法人北陸学園','non_religious','coed','attached','福井県','福井市','jpms_src_051041',45,'active'),
('jpms_s_0742','仁愛女子中学校','じんあいじょしちゅうがっこう',1948,'学校法人仁愛学園','catholic','girls','attached','福井県','福井市','jpms_src_051042',40,'active'),
('jpms_s_0743','福井工業大学附属福井中学校','ふくいこうぎょうだいがくふぞくふくいちゅうがっこう',1977,'学校法人福井工業大学','non_religious','coed','attached','福井県','福井市','jpms_src_051043',35,'active'),
('jpms_s_0744','啓新中学校','けいしんちゅうがっこう',1975,'学校法人啓新学園','non_religious','coed','attached','福井県','福井市','jpms_src_051044',30,'active'),
('jpms_s_0745','福井中学校','ふくいちゅうがっこう',1968,'学校法人福井学園','non_religious','coed','attached','福井県','福井市','jpms_src_051045',25,'active'),
('jpms_s_0746','高志中学校','たかしちゅうがっこう',1977,'学校法人高志学園','non_religious','coed','none','福井県','南越前町','jpms_src_051046',20,'active'),
-- 石川県 (8校)
('jpms_s_0747','北陸学院中学校','ほくりくがくいんちゅうがっこう',1961,'学校法人北陸学院','protestant','coed','attached','石川県','金沢市','jpms_src_051047',45,'active'),
('jpms_s_0748','星稜中学校','せいりょうちゅうがっこう',2017,'学校法人星稜学園','non_religious','coed','linked','石川県','金沢市','jpms_src_051048',30,'active'),
('jpms_s_0749','金沢学院大学附属中学校','かなざわがくいんだいがくふぞくちゅうがっこう',2022,'学校法人金沢学院','non_religious','coed','attached','石川県','金沢市','jpms_src_051050',25,'active'),
('jpms_s_0750','野田部中学校','のたべちゅうがっこう',1986,'野々市市教育委員会','non_religious','coed','none','石川県','野々市市','jpms_src_051054',15,'active'),
('jpms_s_0751','根上中学校','ねあがりちゅうがっこう',1977,'能美市教育委員会','non_religious','coed','none','石川県','能美市','jpms_src_051053',15,'active'),
('jpms_s_0752','松任中学校','まつとうちゅうがっこう',1975,'白山市教育委員会','non_religious','coed','none','石川県','白山市','jpms_src_051054',15,'active'),
('jpms_s_0753','金沢錦丘高等学校附属中学校','かなざわにしきおかこうとうがっこうふぞくちゅうがっこう',2009,'石川県教育委員会','non_religious','coed','linked','石川県','金沢市','jpms_src_051052',20,'active'),
('jpms_s_0754','金沢工業高等専修学校','かなざわこうぎょうこうとうせんしゅうがっこう',1972,'石川県教育委員会','non_religious','coed','none','石川県','金沢市','jpms_src_051049',15,'active'),
-- 富山県 (4校)
('jpms_s_0755','片山学園中学校','かたやまがくえんちゅうがっこう',2005,'学校法人片山学園','non_religious','coed','attached','富山県','富山市','jpms_src_051055',40,'active'),
('jpms_s_0756','富山第一高等学校中学部','とみだいいちこうとうがっこうちゅうがくぶ',1968,'学校法人富山第一学園','non_religious','coed','linked','富山県','富山市','jpms_src_051056',30,'active'),
('jpms_s_0757','高岡第一中学校','たかおかだいいちちゅうがっこう',1977,'高岡市教育委員会','non_religious','coed','none','富山県','高岡市','jpms_src_051057',15,'active'),
('jpms_s_0758','南砺福野高等学校附属中学校','なんとふくののこうとうがっこうふぞくちゅうがっこう',2010,'富山県教育委員会','non_religious','coed','linked','富山県','南砺市','jpms_src_051058',20,'active'),
-- 山梨県 (6校)
('jpms_s_0759','駿台甲府中学校','すんだいこうふちゅうがっこう',1981,'学校法人駿台学園','non_religious','coed','attached','山梨県','甲府市','jpms_src_051059',40,'active'),
('jpms_s_0760','山梨英和中学校','やまなしえいわちゅうがっこう',1880,'学校法人山梨英和学院','protestant','girls','attached','山梨県','甲府市','jpms_src_051060',45,'active'),
('jpms_s_0761','日本大学明誠高等学校中学部','にほんだいがくめいせいこうとうがっこうちゅうがくぶ',2000,'学校法人日本大学','non_religious','coed','linked','山梨県','甲府市','jpms_src_051061',30,'active'),
('jpms_s_0762','帝京第三中学校','ていきょうだいさんちゅうがっこう',1996,'学校法人帝京大学','non_religious','coed','attached','山梨県','甲府市','jpms_src_051062',30,'active'),
('jpms_s_0763','山梨学院大学附属中学校','やまなしがくいんだいがくふぞくちゅうがっこう',1979,'学校法人山梨学院','non_religious','coed','attached','山梨県','甲府市','jpms_src_051063',25,'active'),
('jpms_s_0764','身延山高等学校附属中学校','しんえんざんこうとうがっこうふぞくちゅうがっこう',2012,'学校法人身延山学園','buddhist','coed','linked','山梨県','南部町','jpms_src_051064',20,'active'),
-- 追加記載校 (16校: ID 0765-0779)
('jpms_s_0765','一宮中学校','いちのみやちゅうがっこう',1980,'学校法人一宮学園','non_religious','coed','none','愛知県','一宮市','jpms_src_051065',25,'active'),
('jpms_s_0766','豊川中学校','とよかわちゅうがっこう',1982,'学校法人豊川学園','non_religious','coed','none','愛知県','豊川市','jpms_src_051066',25,'active'),
('jpms_s_0767','浜松開誠館中学校','はままつかいせいかんちゅうがっこう',1983,'学校法人開誠館','non_religious','coed','none','静岡県','浜松市','jpms_src_051067',25,'active'),
('jpms_s_0768','浜松学院中学校','はままつがくいんちゅうがっこう',1977,'学校法人浜松学院','non_religious','coed','none','静岡県','浜松市','jpms_src_051068',25,'active'),
('jpms_s_0769','新潟第一中学校','にいがただいいちちゅうがっこう',1975,'学校法人新潟第一学園','non_religious','coed','none','新潟県','新潟市','jpms_src_051069',25,'active'),
('jpms_s_0770','加藤学園高等学校附属中学校','かとうがくえんこうとうがっこうふぞくちゅうがっこう',1988,'学校法人加藤学園','non_religious','coed','linked','静岡県','富士市','jpms_src_051070',25,'active'),
('jpms_s_0771','飯山中学校','いいやまちゅうがっこう',1963,'飯山市教育委員会','non_religious','coed','none','長野県','飯山市','jpms_src_051071',15,'active'),
('jpms_s_0772','関市立中央中学校','せきしりつちゅうおうちゅうがっこう',1972,'関市教育委員会','non_religious','coed','none','岐阜県','関市','jpms_src_051073',15,'active'),
('jpms_s_0773','勝山中学校','かつやまちゅうがっこう',1980,'勝山市教育委員会','non_religious','coed','none','福井県','勝山市','jpms_src_051074',15,'active'),
('jpms_s_0774','小松市立小松中学校','こまつしりつこまつちゅうがっこう',1970,'小松市教育委員会','non_religious','coed','none','石川県','小松市','jpms_src_051075',15,'active'),
('jpms_s_0775','南砺市立南砺中学校','なんとしりつなんとちゅうがっこう',1963,'南砺市教育委員会','non_religious','coed','none','富山県','南砺市','jpms_src_051076',15,'active'),
('jpms_s_0776','甲府市立甲府中学校','こうふしりつこうふちゅうがっこう',1947,'甲府市教育委員会','non_religious','coed','none','山梨県','甲府市','jpms_src_051077',15,'active'),
('jpms_s_0777','富士市立吉原中学校','ふじしりつよしわらちゅうがっこう',1960,'富士市教育委員会','non_religious','coed','none','静岡県','富士市','jpms_src_051078',15,'active'),
('jpms_s_0778','長野県林中学校','ながのけんりんちゅうがっこう',1966,'長野県教育委員会','non_religious','coed','none','長野県','長野市','jpms_src_051031',15,'active'),
('jpms_s_0779','新潟南高等学校附属中学校','にいがたみなみこうとうがっこうふぞくちゅうがっこう',2005,'学校法人新潟南学園','non_religious','coed','linked','新潟県','新潟市','jpms_src_051079',20,'active');
