-- JPMS-DB Phase 2.5 W44: 九州8県と沖縄の私立中学校
-- 対象地域: 福岡県・佐賀県・長崎県・熊本県・大分県・宮崎県・鹿児島県・沖縄県
-- ID範囲: jpms_s_0870 〜 jpms_s_0917（48校）
-- SourceID範囲: jpms_src_054001 〜 jpms_src_054048

-- ============================================================
-- SOURCE REGISTRATION
-- ============================================================

INSERT INTO jpms_sources (id, source_type, title, author, accessed_at, publication_year, rights_status, primary_or_secondary, reliability_score, note) VALUES
('jpms_src_054001','school_website','久留米大学附設中学校','学校法人久留米大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1950年'),
('jpms_src_054002','school_website','西南学院中学校','学校法人西南学院',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1916年'),
('jpms_src_054003','school_website','福岡大学附属大濠中学校','福岡大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1996年'),
('jpms_src_054004','school_website','福岡雙葉中学校','学校法人福岡雙葉学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1933年'),
('jpms_src_054005','school_website','福岡女学院中学校','学校法人福岡女学院',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1885年'),
('jpms_src_054006','school_website','明治学園中学校','学校法人明治学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1901年'),
('jpms_src_054007','school_website','福岡海星女子学園中学校','学校法人海星学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1946年'),
('jpms_src_054008','school_website','敬愛中学校','学校法人敬愛学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1955年'),
('jpms_src_054009','school_website','東福岡自彊館中学校','学校法人東福岡学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1908年'),
('jpms_src_054010','school_website','九州国際大学附属中学校','学校法人九州国際大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1969年'),
('jpms_src_054011','school_website','上智福岡中学校','学校法人上智福岡',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1928年'),
('jpms_src_054012','school_website','純真中学校','学校法人純真学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1964年'),
('jpms_src_054013','school_website','筑陽学園中学校','学校法人筑陽学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1986年'),
('jpms_src_054014','school_website','八代第一中学校','学校法人八代学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1925年'),
('jpms_src_054015','school_website','弘学館中学校','学校法人弘学館',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1987年'),
('jpms_src_054016','school_website','東明館中学校','学校法人東明館',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1988年'),
('jpms_src_054017','school_website','龍谷中学校','学校法人佐賀龍谷学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'buddhist 1878年'),
('jpms_src_054018','school_website','佐賀清和中学校','学校法人佐賀清和学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1985年'),
('jpms_src_054019','school_website','海星中学校','学校法人海星学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1892年'),
('jpms_src_054020','school_website','青雲中学校','学校法人青雲学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1975年'),
('jpms_src_054021','school_website','長崎日本大学中学校','学校法人日本大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1963年'),
('jpms_src_054022','school_website','活水中学校','学校法人活水学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1879年'),
('jpms_src_054023','school_website','純心中学校','学校法人長崎純心学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1954年'),
('jpms_src_054024','school_website','長崎南山中学校','学校法人南山学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1948年'),
('jpms_src_054025','school_website','真和中学校','学校法人真和学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'buddhist 1960年'),
('jpms_src_054026','school_website','熊本マリスト学園中学校','学校法人熊本マリスト学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1963年'),
('jpms_src_054027','school_website','熊本信愛女学院中学校','学校法人熊本信愛学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1956年'),
('jpms_src_054028','school_website','九州学院中学校','学校法人九州学院',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1911年'),
('jpms_src_054029','school_website','ルーテル学院中学校','学校法人九州ルーテル学院',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1926年'),
('jpms_src_054030','school_website','岩田中学校','学校法人岩田学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1900年'),
('jpms_src_054031','school_website','大分東明高等学校向陽中学校','学校法人平松学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 2006年'),
('jpms_src_054032','school_website','大分高等学校中学部','学校法人大分高等学校',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1963年'),
('jpms_src_054033','school_website','宮崎日本大学中学校','学校法人日本大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1963年'),
('jpms_src_054034','school_website','日章学園中学校','学校法人日章学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1986年'),
('jpms_src_054035','school_website','宮崎学園中学校','学校法人宮崎学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1980年'),
('jpms_src_054036','school_website','宮崎国際大学附属中学校','学校法人宮崎国際大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 2008年'),
('jpms_src_054037','school_website','ラ・サール中学校','学校法人ラ・サール学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1956年'),
('jpms_src_054038','school_website','志學館中等部','学校法人志學館学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1988年'),
('jpms_src_054039','school_website','鹿児島純心女子中学校','学校法人純心学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1952年'),
('jpms_src_054040','school_website','鹿児島育英館中学校','学校法人育英館',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1984年'),
('jpms_src_054041','school_website','池田学園池田中学校','学校法人池田学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1953年'),
('jpms_src_054042','school_website','鹿児島実業高等学校中学部','学校法人加治木学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1963年'),
('jpms_src_054043','school_website','沖縄尚学高等学校附属中学校','学校法人沖縄尚学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1985年'),
('jpms_src_054044','school_website','興南中学校','学校法人興南学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1985年'),
('jpms_src_054045','school_website','昭和薬科大学附属中学校','学校法人昭和薬科大学',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'non_religious 1986年'),
('jpms_src_054046','school_website','沖縄カトリック中学校','学校法人沖縄カトリック学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'catholic 1990年'),
('jpms_src_054047','school_website','沖縄三育中学校','学校法人沖縄三育学園',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1978年'),
('jpms_src_054048','school_website','沖縄キリスト教学院中学校','学校法人沖縄キリスト教学院',datetime('now'),NULL,'copyrighted_permission_required','primary',95,'protestant 1950年');

-- ============================================================
-- SCHOOL DATA
-- ============================================================


INSERT INTO jpms_schools (id, name_ja, name_kana, establishment_year, school_corporation, religious_affiliation, founding_philosophy, gender_type, integrated_type, location_pref, location_city, primary_source_id, data_completeness, status) VALUES
('jpms_s_0870','久留米大学附設中学校','くるめだいがくふせつちゅうがっこう',1950,'学校法人久留米大学','non_religious','人材育成','coed','attached','福岡県','久留米市','jpms_src_054001',30,'active'),
('jpms_s_0871','西南学院中学校','せいなんがくいんちゅうがっこう',1916,'学校法人西南学院','protestant','人材育成','coed','attached','福岡県','福岡市','jpms_src_054002',30,'active'),
('jpms_s_0872','福岡大学附属大濠中学校','ふくおかだいがくふぞくおおほりちゅうがっこう',1996,'福岡大学','non_religious','人材育成','coed','attached','福岡県','福岡市','jpms_src_054003',30,'active'),
('jpms_s_0873','福岡雙葉中学校','ふくおかふたばちゅうがっこう',1933,'学校法人福岡雙葉学園','catholic','人材育成','girls','attached','福岡県','福岡市','jpms_src_054004',30,'active'),
('jpms_s_0874','福岡女学院中学校','ふくおかじょがくいんちゅうがっこう',1885,'学校法人福岡女学院','protestant','人材育成','girls','attached','福岡県','福岡市','jpms_src_054005',30,'active'),
('jpms_s_0875','明治学園中学校','めいじがくえんちゅうがっこう',1901,'学校法人明治学園','non_religious','人材育成','coed','attached','福岡県','筑紫野市','jpms_src_054006',30,'active'),
('jpms_s_0876','福岡海星女子学園中学校','ふくおかかいせいじょしがくえんちゅうがっこう',1946,'学校法人海星学園','catholic','人材育成','girls','attached','福岡県','福岡市','jpms_src_054007',30,'active'),
('jpms_s_0877','敬愛中学校','けいあいちゅうがっこう',1955,'学校法人敬愛学園','non_religious','人材育成','girls','attached','福岡県','福岡市','jpms_src_054008',30,'active'),
('jpms_s_0878','東福岡自彊館中学校','ひがしふくおかじきょうかんちゅうがっこう',1908,'学校法人東福岡学園','non_religious','人材育成','coed','attached','福岡県','福岡市','jpms_src_054009',30,'active'),
('jpms_s_0879','九州国際大学附属中学校','きゅうしゅうこくさいだいがくふぞくちゅうがっこう',1969,'学校法人九州国際大学','non_religious','人材育成','coed','attached','福岡県','北九州市','jpms_src_054010',30,'active'),
('jpms_s_0880','上智福岡中学校','じょうちふくおかちゅうがっこう',1928,'学校法人上智福岡','catholic','人材育成','coed','attached','福岡県','福岡市','jpms_src_054011',30,'active'),
('jpms_s_0881','純真中学校','じゅんしんちゅうがっこう',1964,'学校法人純真学園','non_religious','人材育成','girls','attached','福岡県','福岡市','jpms_src_054012',30,'active'),
('jpms_s_0882','筑陽学園中学校','ちくようがくえんちゅうがっこう',1986,'学校法人筑陽学園','non_religious','人材育成','coed','attached','福岡県','太宰府市','jpms_src_054013',30,'active'),
('jpms_s_0883','八代第一中学校','やつしろだいいちちゅうがっこう',1925,'学校法人八代学園','non_religious','人材育成','coed','attached','福岡県','八代市','jpms_src_054014',30,'active'),
('jpms_s_0884','弘学館中学校','こうがくかんちゅうがっこう',1987,'学校法人弘学館','non_religious','人材育成','coed','attached','佐賀県','佐賀市','jpms_src_054015',30,'active'),
('jpms_s_0885','東明館中学校','とうめいかんちゅうがっこう',1988,'学校法人東明館','non_religious','人材育成','coed','attached','佐賀県','基山町','jpms_src_054016',30,'active'),
('jpms_s_0886','龍谷中学校','りゅうこくちゅうがっこう',1878,'学校法人佐賀龍谷学園','buddhist','人材育成','coed','attached','佐賀県','佐賀市','jpms_src_054017',30,'active'),
('jpms_s_0887','佐賀清和中学校','さがきよわちゅうがっこう',1985,'学校法人佐賀清和学園','non_religious','人材育成','coed','attached','佐賀県','小城市','jpms_src_054018',30,'active'),
('jpms_s_0888','海星中学校','かいせいちゅうがっこう',1892,'学校法人海星学園','catholic','人材育成','coed','attached','長崎県','長崎市','jpms_src_054019',30,'active'),
('jpms_s_0889','青雲中学校','せいうんちゅうがっこう',1975,'学校法人青雲学園','non_religious','人材育成','coed','attached','長崎県','時津町','jpms_src_054020',30,'active'),
('jpms_s_0890','長崎日本大学中学校','ながさきにほんだいがくちゅうがっこう',1963,'学校法人日本大学','non_religious','人材育成','coed','attached','長崎県','諫早市','jpms_src_054021',30,'active'),
('jpms_s_0891','活水中学校','かつすいちゅうがっこう',1879,'学校法人活水学園','protestant','人材育成','girls','attached','長崎県','長崎市','jpms_src_054022',30,'active'),
('jpms_s_0892','純心中学校','じゅんしんちゅうがっこう',1954,'学校法人長崎純心学園','catholic','人材育成','girls','attached','長崎県','長崎市','jpms_src_054023',30,'active'),
('jpms_s_0893','長崎南山中学校','ながさきみなみやまちゅうがっこう',1948,'学校法人南山学園','catholic','人材育成','coed','attached','長崎県','長崎市','jpms_src_054024',30,'active'),
('jpms_s_0894','真和中学校','しんわちゅうがっこう',1960,'学校法人真和学園','buddhist','人材育成','coed','attached','熊本県','熊本市','jpms_src_054025',30,'active'),
('jpms_s_0895','熊本マリスト学園中学校','くまもとまりすとがくえんちゅうがっこう',1963,'学校法人熊本マリスト学園','catholic','人材育成','coed','attached','熊本県','熊本市','jpms_src_054026',30,'active'),
('jpms_s_0896','熊本信愛女学院中学校','くまもとしんあいじょがくいんちゅうがっこう',1956,'学校法人熊本信愛学園','catholic','人材育成','girls','attached','熊本県','熊本市','jpms_src_054027',30,'active'),
('jpms_s_0897','九州学院中学校','きゅうしゅうがくいんちゅうがっこう',1911,'学校法人九州学院','protestant','人材育成','coed','attached','熊本県','熊本市','jpms_src_054028',30,'active'),
('jpms_s_0898','ルーテル学院中学校','るーてるがくいんちゅうがっこう',1926,'学校法人九州ルーテル学院','protestant','人材育成','coed','attached','熊本県','熊本市','jpms_src_054029',30,'active'),
('jpms_s_0899','岩田中学校','いわたちゅうがっこう',1900,'学校法人岩田学園','non_religious','人材育成','coed','attached','大分県','大分市','jpms_src_054030',30,'active'),
('jpms_s_0900','大分東明高等学校向陽中学校','おおいたとうめいこうとうがっこうこうようちゅうがっこう',2006,'学校法人平松学園','non_religious','人材育成','coed','attached','大分県','大分市','jpms_src_054031',30,'active'),
('jpms_s_0901','大分高等学校中学部','おおいたこうとうがっこうちゅうがくぶ',1963,'学校法人大分高等学校','non_religious','人材育成','coed','attached','大分県','大分市','jpms_src_054032',30,'active'),
('jpms_s_0902','宮崎日本大学中学校','みやざきにほんだいがくちゅうがっこう',1963,'学校法人日本大学','non_religious','人材育成','coed','attached','宮崎県','宮崎市','jpms_src_054033',30,'active'),
('jpms_s_0903','日章学園中学校','にっしょうがくえんちゅうがっこう',1986,'学校法人日章学園','non_religious','人材育成','coed','attached','宮崎県','宮崎市','jpms_src_054034',30,'active'),
('jpms_s_0904','宮崎学園中学校','みやざきがくえんちゅうがっこう',1980,'学校法人宮崎学園','non_religious','人材育成','coed','attached','宮崎県','宮崎市','jpms_src_054035',30,'active'),
('jpms_s_0905','宮崎国際大学附属中学校','みやざきこくさいだいがくふぞくちゅうがっこう',2008,'学校法人宮崎国際大学','non_religious','人材育成','coed','attached','宮崎県','宮崎市','jpms_src_054036',30,'active'),
('jpms_s_0906','ラ・サール中学校','らさーるちゅうがっこう',1956,'学校法人ラ・サール学園','catholic','人材育成','boys','attached','鹿児島県','鹿児島市','jpms_src_054037',30,'active'),
('jpms_s_0907','志學館中等部','しがくかんちゅうとうぶ',1988,'学校法人志學館学園','non_religious','人材育成','coed','attached','鹿児島県','鹿児島市','jpms_src_054038',30,'active'),
('jpms_s_0908','鹿児島純心女子中学校','かごしまじゅんしんじょしちゅうがっこう',1952,'学校法人純心学園','catholic','人材育成','girls','attached','鹿児島県','鹿児島市','jpms_src_054039',30,'active'),
('jpms_s_0909','鹿児島育英館中学校','かごしまいくえいかんちゅうがっこう',1984,'学校法人育英館','non_religious','人材育成','coed','attached','鹿児島県','鹿児島市','jpms_src_054040',30,'active'),
('jpms_s_0910','池田学園池田中学校','いけだがくえんいけだちゅうがっこう',1953,'学校法人池田学園','non_religious','人材育成','coed','attached','鹿児島県','鹿児島市','jpms_src_054041',30,'active'),
('jpms_s_0911','鹿児島実業高等学校中学部','かごしまじつぎょうこうとうがっこうちゅうがくぶ',1963,'学校法人加治木学園','non_religious','人材育成','coed','attached','鹿児島県','加治木町','jpms_src_054042',30,'active'),
('jpms_s_0912','沖縄尚学高等学校附属中学校','おきなわしょうがくこうとうがっこうふぞくちゅうがっこう',1985,'学校法人沖縄尚学','non_religious','人材育成','coed','attached','沖縄県','那覇市','jpms_src_054043',30,'active'),
('jpms_s_0913','興南中学校','こうなんちゅうがっこう',1985,'学校法人興南学園','non_religious','人材育成','coed','attached','沖縄県','那覇市','jpms_src_054044',30,'active'),
('jpms_s_0914','昭和薬科大学附属中学校','しょうわやっかだいがくふぞくちゅうがっこう',1986,'学校法人昭和薬科大学','non_religious','人材育成','coed','attached','沖縄県','浦添市','jpms_src_054045',30,'active'),
('jpms_s_0915','沖縄カトリック中学校','おきなわかとりっくちゅうがっこう',1990,'学校法人沖縄カトリック学園','catholic','人材育成','coed','attached','沖縄県','那覇市','jpms_src_054046',30,'active'),
('jpms_s_0916','沖縄三育中学校','おきなわさんいくちゅうがっこう',1978,'学校法人沖縄三育学園','protestant','人材育成','coed','attached','沖縄県','南城市','jpms_src_054047',30,'active'),
('jpms_s_0917','沖縄キリスト教学院中学校','おきなわきりすときょうがくいんちゅうがっこう',1950,'学校法人沖縄キリスト教学院','protestant','人材育成','coed','attached','沖縄県','那覇市','jpms_src_054048',30,'active');

-- Total: 48 schools registered
